### ISSUE TITLE
Database models need docstrings

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#1]
I'm not privy to the details of the different tables, someone who is will need to provide docstrings.

**Comment by Koeng101** [comment]
on it.

**Comment by vsoch** [comment]
Assigned! It will be a bit while I work through the current fixes - I'll update you when I'm all done (and I realize it's only 6am in California so I hope you are asleep!)

**Comment by vsoch** [comment]
This is reasonably done, closing issue.
