### ISSUE TITLE
Add a toggle switch to list Shipments as complete [low priority]

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#101]
**Is your feature request related to a problem? Please describe.**
Some old shipments are listed as processing on the Shipments Dashboard because we don't have the shipping labels for them anymore.

**Describe the solution you'd like**
I'd like a way to mark shipments without labels as "complete" on the dashboard. A toggle switch would be sufficient. For orders with labels, the current software behavior should remain the same - i.e., the label should still indicate that the shipment is complete.

**Describe alternatives you've considered**
If you see a better implementation, feel free to move in that direction. I only care that I can sort out which orders are actually complete :)

Anything else?
<img width="1163" alt="Screen Shot 2019-10-17 at 10 09 57 AM" src="https://user-images.githubusercontent.com/31907124/67031497-89f16400-f0c6-11e9-8e33-9271bdaf5b0d.png">

**Comment by vsoch** [comment]
Oh good idea! So I just pushed a change so that orders with the boolean "received" that is updated at the same time that the label is generated:

```python
    if not order.label:

        # If we are successful, we can retrieve the shipping label
        label = shippo.Transaction.retrieve(order.transaction['object_id'], 
                                            api_key=SHIPPO_TOKEN)
        order.add_label(label)

        # Received flag indicates it was processed
        order.received = True
        order.save()
```
so you should be able to manipulate received in the order details pages to toggle those from Processing to complete. Let me know if that works!

**Comment by hverdonk** [comment]
That totally solved the problem! Thank you.
