### ISSUE TITLE
Shipment label generation fails

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#104]
**Describe the bug**
When creating a shipment for Isaac's pOpen_v3 test order, I was able to purchase a label, but when it came time to generate that label, I received the error that the dry ice weight exceeded the package weight. 

I set the total package weight to be 7 and selected 5 pounds of dry ice, and the software allowed me to proceed to the rate selection page and select a rate. It was only when I actually clicked "generate label" on the following page that I received the error.

**To Reproduce**
Currently, if you visit [the order itself](https://freegenes.dev/o/details/a8953111-b581-4c72-9616-55fa4d51d912) and select "track shipment," you should see the resulting error.

**Comment by vsoch** [comment]
It looks like the original transaction turned out to be invalid:

```
 {
  "billing": {
    "payments": []
  },
  "commercial_invoice_url": null,
  "eta": null,
  "label_url": "",
  "messages": [
    {
      "code": "2494",
      "source": "FedEx",
      "text": "ERROR: Package dry ice weight cannot be greater than package weight."
    }
  ],
  "metadata": "",
  "object_created": "2019-10-25T22:09:23.584Z",
  "object_id": "686c3b8710b544da8062528cf60eb790",
  "object_owner": "drew_endy_lab@stanford.edu",
  "object_state": "VALID",
  "object_updated": "2019-10-25T22:09:25.237Z",
  "order": null,
  "parcel": "e39aefbbd2b543c5bae07485f22347e2",
  "rate": "561525c44c704133a481708ad3abd29c",
  "status": "ERROR",
  "test": false,
  "tracking_number": "",
  "tracking_status": "UNKNOWN",
  "tracking_url_provider": ""
}
```
I'm walking through it now - could you tell me the rate that you chose?

**Comment by hverdonk** [comment]
I selected the "Standard Overnight" FedEx rate.

**Comment by hverdonk** [comment]
Trying again, it appears that the transaction works for 1lb of dry ice. As irritating as this newest Shippo bug is, I'm content to just remove the 5lb option and ship with less dry ice to get around it.

**Comment by vsoch** [comment]
okay, and note that I sent a fairly long issue to Shippo (with you cc'd) over the weekend for this.

**Comment by hverdonk** [comment]
Thanks for doing that. I'm fine with closing this issue now, since a solution has been found. Would you please remove the 5lb dry ice option?

**Comment by vsoch** [comment]
Removed.
