### ISSUE TITLE
Editing an imported Shippo order in the Django admin panel triggers an error.

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#111]
**Describe the bug**
I tested the order import system on Jenny Molloy's order to the University of Cambridge. While the order did appear in my Shipments dashboard, I was unable to edit/add information to the order in the Django admin panel. Admittedly, the error may be triggered because the original order exists, but I don't feel confident deleting the original until the new one is complete.

**To Reproduce**
In Django admin, click on the OpenEnzyme - Cambridge order associated with my username (hverdonk). Make edits to either the date shipped, date ordered, or notes fields and try to save the changes.

**Expected behavior**
The desired changes should be made without triggering an error.

**Comment by vsoch** [comment]
I'm glad you didn't delete it, because it's actually unrelated to what you mentioned.  I just pushed a fix, but now it won't let you save because you are only allowed one pending order (the cart):
```
User hverdonk has a pending order, only one cart is allowed.
```
What I'll do is a check for if the user is a staff or admin, and we can allow the staff or admin to have more than one.

**Comment by vsoch** [comment]
Actually, could you just set the OpenEnzyme order (which appears empty) to be received/ordered? Or delete it? It would be cleaner logic (in that an admin could technically order something) to not make an exception. Let me know if that works, in summary:

 - set OpenEnzyme order to ordered = True 
 - edit the Cambridge order as you wanted to before (I think notes would be required)

**Comment by hverdonk** [comment]
I'll delete the extra order - I put it in my cart a while ago as a test and deleted it from my cart, but it didn't delete it in the admin panel.

**Comment by hverdonk** [comment]
Just updated the Cambridge order and it worked perfectly.

**Comment by vsoch** [comment]
Awesome! Glad to hear.
