### ISSUE TITLE
Change "Zip" to "Postal Code" [Low Priority]

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#116]
On both the customer-facing distribution order form and on the admin "Create Shipment" page, we'd like to change all mentions of "zip" or "zip code" to say "postal code" instead, to better support international users.

**Comment by hverdonk** [comment]
The customer checkout form:
<img width="807" alt="Screen Shot 2019-11-06 at 11 29 23 AM" src="https://user-images.githubusercontent.com/31907124/68331130-49638580-0089-11ea-909b-cc1453950609.png">

The Admin "Create Shipment" page:
<img width="392" alt="Screen Shot 2019-11-06 at 11 32 13 AM" src="https://user-images.githubusercontent.com/31907124/68331175-5ed8af80-0089-11ea-9233-feab36c81786.png">

**Comment by vsoch** [comment]
Done https://github.com/vsoch/freegenes/commit/8c6140dfacf9cf9aa60fe71e386078259553ad1b
