### ISSUE TITLE
Removing an item from the cart does not delete it from the Django admin "orders" page.

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#117]
**Describe the bug**
When I delete an item from my cart, the associated "order" in Django admin is not removed.

**To Reproduce**
On freegenes.dev, add an item to the user's cart, then immediately delete it. Then, go to the [Django admin orders page](https://freegenes.dev/admin/orders/order/), and see the order associated with that user has not also been deleted.

**Expected behavior**
Removing an item from the cart should remove the corresponding "order" in Django admin.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
Ah yes that's a bug, we need to check if the order has one item, and then if it's removed, delete the order. Let me see if I can fix this up.

**Comment by vsoch** [comment]
okay should be fixed, give it a try and close the issue if it's resolved.

**Comment by hverdonk** [comment]
It works, thank you!
