### ISSUE TITLE
Add "Country" & "Special Information" field to shipping pages.

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#118]
**Is your feature request related to a problem? Please describe.**
For international shipments, we need to know the requester's country to ship to them. Currently, there is no place for a requester or a shipper to input that information.

Also, if a recipient has additional concerns about package deliveries (e.g., packages cannot be delivered after 5pm), they should have a place to request that.

**Describe the solution you'd like**
I'd like both fields to be added to the Order Checkout page and the Create Shipment page.

For the Create Shipment page specifically, both fields should be present for the "Shipping to" half, but the "Shipping from" half can just have the Country of origin field.

**Describe alternatives you've considered**
I can't think of any alternatives that would capture the information we need.

Anything else?

**Comment by vsoch** [comment]
Since the lab can select to use the same address, and since it's likely that the country will be missed, I'm adding the country to both fields, and I'm putting comments on both too so that they can fill out whichever they see (and won't miss it).

**Comment by vsoch** [comment]
But actually, if someone deploys FreeGenes outside of the US, it won't hurt to have the From country. I'll add it for that.

**Comment by vsoch** [comment]
okay this should be all set. I need to run for a few hours (I have a meeting and then an interview with someone) but I just updated the server and I'll be back after that!

**Comment by hverdonk** [comment]
Exactly why I wanted the country field for the shipper :). Alternatively, there could be a default address for the shipper (including the country) in the config file.
