### ISSUE TITLE
Make cart items easier to edit/delete

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#119]
**Is your feature request related to a problem? Please describe.**
When viewing the contents of the cart, it isn't obvious that there's an edit/delete button, as both buttons are off the page and obscured unless the user realizes they can scroll to the side and see it.

**Describe the solution you'd like**
Rather than a scroll bar, can we have the order description wrap to fit on the page?

**Describe alternatives you've considered**
We could make it more obvious that it's possible to scroll to the side, but that seems inelegant.

Anything else?

**Comment by vsoch** [comment]
Huh, can you show me a screen shot? It looks okay to me - the small trash can and edit are cleanly in the row.

![image](https://user-images.githubusercontent.com/814322/68334250-39a76980-00a8-11ea-8874-fe8aa1f6442c.png)

It might be a browser issue.

**Comment by hverdonk** [comment]
<img width="1280" alt="Screen Shot 2019-11-06 at 11 59 07 AM" src="https://user-images.githubusercontent.com/31907124/68336848-1f639080-0094-11ea-80e8-81db1c31e02f.png">
<img width="1280" alt="Screen Shot 2019-11-06 at 12 00 06 PM" src="https://user-images.githubusercontent.com/31907124/68336854-2094bd80-0094-11ea-90e6-af7b0cfbf12c.png">

**Comment by hverdonk** [comment]
You seem to be viewing an older version of the description

**Comment by vsoch** [comment]
Ah so the issue is the description field - the reason it looks ok for me is because the field is empty. This is the reason that I originally truncated it (and you would need to view the details to see the full thing). I'm not sure how to handle text wrapping in a table cell but I can try looking into it.

**Comment by hverdonk** [comment]
If the text absolutely can't be wrapped, another possibility is to move the Description field to the far right of the table.

**Comment by vsoch** [comment]
Fixed!
