### ISSUE TITLE
Plate (and other object) search functions

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#12]
Based on what Keoni mentioned:

> A plate with wells cannot be deleted. HOWEVER, you can change the container of the plate to be in the trash, and so it won't be searched on anymore, but simply exist for historical tracking.

We would want to provide a function to Plate (and any other relevant objects that can be trashed) that searches over all except for those with status Trashed. I'll implement this to start as Plate.search.

**Comment by vsoch** [comment]
Depending on how often this query is done, it could also just be done as:

```python
from django.db.models import Q
Plate.objects.filter(~Q(plate_status ="Trashed")
```

**Comment by Koeng101** [comment]
I think the simple solution you posted works well enough for now.
