### ISSUE TITLE
Cart "Edit" button takes users to the Django admin page

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#120]
**Describe the bug**
Editing an order in a user's cart takes that user to the Django admin page for that distribution.

**To Reproduce**
Put an order in the cart, then view the cart. On the order, click "Edit"

**Expected behavior**
"Edit" should let one change the value of "PlateSets Quantity" to order more copies of a distribution.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
I don't think a non staff / superuser can see the edit button - could you login with someone that isn't your account and verify this? it's only there for your editing.

Also, I remember discussing this with @Koeng101 early on - we don't have a number of distributions implemented for the cart - it's basically add one, or delete it. Adding this extra functionality is non trivial as we'd need to refactor the cart so I think it's out of scope here, and we had already discussed this point early on.

**Comment by Koeng101** [comment]
Yea I think only ordering 1 distribution was a constraint we put on the system early to make it easier to functionally operate.
