### ISSUE TITLE
"Date Ordered" doesn't autopopulate when users generate an order

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#121]
**Describe the bug**
When I receive a user's order in the "Shipments" dashboard, the "date ordered" field does not populate automatically with the date the user made the order. Instead, there is no data in the field.

**To Reproduce**
Create an order through freegenes.dev using dummy addresses, MTAs, etc. Submit the order. Then, view the order on the Shipments dashboard.

**Expected behavior**
The submission date should be attached to the order when the user checks out.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
This was a manual field that I added (with expectation that you would fill it out) so I didn't know you wanted this functionality - thanks for telling me!

**Comment by vsoch** [comment]
okay all set. https://github.com/vsoch/freegenes/commit/f70c327d30977f24b277e5f9a99560761a37a7eb
