### ISSUE TITLE
Searching as non-login user

### ISSUE THREAD

**Issue by marc4-stanford** [vsoch/freegenes#123]
I went the the freegenes.dev page and searched for "open" I got these results.
![Screen Shot 2019-11-07 at 8 02 05 AM](https://user-images.githubusercontent.com/42281767/68405512-170f6200-0135-11ea-9bd7-20d15d0770d0.png)

Can we remove Containers and Institutions from the search?

Thanks.

**Comment by vsoch** [comment]
Yep sure thing! I’ll be able to jump on this in a few minutes.

**Comment by marc4-stanford** [comment]
Thanks. 

/marc

**Comment by vsoch** [comment]
okay testing locally first - here is the search for open as a non-staff / non-superuser or not logged in user:

![image](https://user-images.githubusercontent.com/814322/68406480-e8eb4b80-014f-11ea-921c-43cd5c2afac9.png)

Will push and update server next.

**Comment by marc4-stanford** [comment]
Pretty

**Comment by vsoch** [comment]
Closed with https://github.com/vsoch/freegenes/commit/2d027d03d14c5b871fff8a7b3e2c8bb100f11402
