### ISSUE TITLE
Number of Available Parts

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#125]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
On the Dashboard, and above the search results, I would like to see the number of available parts in this Bionet Node. The available parts are defined as the number of unqiue parts available through all distributions.

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
Definitely good to showcase the contents! Could you clarify what you would want, interface wise? The parts is already the first entry of the green boxes:

![image](https://user-images.githubusercontent.com/814322/68515157-f850be80-024d-11ea-8163-32cdde107057.png)

And above we see there are 2991. Clicking on the box goes directly to the catalog with a search box at the top.

**Comment by Koeng101** [comment]
We want a box that is more obvious (separate from those ones) that specifically show the available parts (so parts that are available in distributions). Those parts are globally known, we just want the ones that people can get from us

**Comment by vsoch** [comment]
Can you mock up an example (draw, google slides or similar site) to show what you are looking for exactly?

**Comment by Koeng101** [comment]
Sorry for the rethink, but this number might be nice to proudly put at the top of the site, like this:

![379C595E-EE5B-46D5-BED2-B59C004B29A4](https://user-images.githubusercontent.com/2896607/68515947-73f34100-0237-11ea-8574-f627b8d505b9.jpeg)

I’m thinking some kind of nice popping box with “Available Parts”. Maybe you could click it to be brought to distributions (or that could be later if hard)

**Comment by vsoch** [comment]
Ohh I see! You mean at the very tippy top in the navigation bar! Sure I can give that a go :) Two questions:
 
 - Should it link to the same Parts catalog?
 - Do we still want to have Parts as a green box (we can put something else of interest)

**Comment by Koeng101** [comment]
1. It should link to the Distributions catalog (since these are just parts that belong in Distributions)
2. I think parts should still be in the green box, since it is interesting to see the difference between the available parts and total number of parts

**Comment by vsoch** [comment]
okay! One more question - do you want that box to show on the navbar globally across the site, or just on the parts search and dashboard pages?

**Comment by Koeng101** [comment]
Globally sounds awesome!

**Comment by vsoch** [comment]
okay I'm doing some overly slow querying to test that it is the case that we can use the first plate as a representative for the parts in the rest. This query (exhaustively going through all distributions -> plateset -> plate -> well -> sample -> part:

```python
     parts = set() 
    ...:     for distribution in Distribution.objects.all(): 
    ...:         for plateset in distribution.platesets.all(): 
    ...:             # Each plate should be the same, so we look at the first 
    ...:             for plate in plateset.plates.all():           
    ...:                 for well in plate.wells.all(): 
    ...:                     for sample in well.sample_wells.all(): 
    ...:                         parts.add(sample.part.gene_id) 
```

Returns 43 parts, meaning that 43 are available out of the (just under 3k)

```python
len(parts) 
43
```
We get the same answer when we do the (much faster):

```python
def get_unique_parts():
    '''we use this function to get parts associated with a distribution (meaning
       that they can be requested. This is different from the total parts in
       FreeGenes, which would be this query:

       Part.objects.values('gene_id').distinct().count()
    '''
    parts = set()
    for distribution in Distribution.objects.all():
        for plateset in distribution.platesets.all():
            # Each plate should be the same, so we look at the first
            plate = plateset.plates.first()          
            for well in plate.wells.all():
                parts.add(well.sample_wells.first().part.gene_id)
    return parts         
```

And then confirm they are the same
```python
parts = get_unique_parts()
len(parts)
43
```

**Comment by vsoch** [comment]
![image](https://user-images.githubusercontent.com/814322/68529941-c6813b80-02d1-11ea-8f68-d841ba315776.png)
