### ISSUE TITLE
Allow requester to see the status of shipment

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#127]
**Is your feature request related to a problem? Please describe.**
Requesters can't see the status of their orders (As far as I know)

**Describe the solution you'd like**
A way for requesters to see the status of their orders. This seems like it would be most convenient to have a section under your user profile that says "Orders", that you can click on and be lead to your current orders. Those orders would basically just be in a table, which shows the status of each (processing, shipped, etc)

**Describe alternatives you've considered**
The status could just be emailed to them over time (with a way to opt out), or could be in a different page

Anything else?
Will likely need for #126 to be solved first

**Comment by vsoch** [comment]
This is actually all set - the "orders" view will show the current user cart and below the list of previous orders, and one of the columns is the Tracking id. I don't have any tracking ids in my current testing server, but if I did, I'd see the updated statuses and tracking there. 

![image](https://user-images.githubusercontent.com/814322/68533214-63080580-02f3-11ea-9f78-e02b139c1e9e.png)
