### ISSUE TITLE
When test in Google Cloud, add django-storages

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#13]
We want the containers to be ephemeral (and not rely on any given filesystem) but also be easy to develop locally (not require setting up cloud storage / credentials for running locally). Or actually, we'd want to give any user the option to deploy it as they see fit! A nice solution is to use [django-storages](https://github.com/jschneier/django-storages) which can (with a custom function) route a file object to the local filesystem or local storage, depending on how the deployment gets configured. I'll add/test this when it's ready for moving into the cloud, leaving as a todo for now.

**Comment by Koeng101** [comment]
Makes sense to me. Usually when I run flask I still interact with a staging/test database elsewhere. I'll talk to Marc about getting Google Cloud still going

**Comment by vsoch** [comment]
There's a process that is managed by the SOM to get on Google Cloud, so please hold off on creating projects / credit cards, we'd want it under that umbrella to get the support, etc.

**Comment by vsoch** [comment]
I’ll get this info for you guys ASAP.

**Comment by Koeng101** [comment]
Got it. Will wait.

**Comment by vsoch** [comment]
just sent in an email!

**Comment by vsoch** [comment]
This is a larger test (that will potentially funk up the current database) so I'm going to wait until after the demonstration to the lab (likely over the weekend / into next week) to test out changing the back end storage strategy.

**Comment by vsoch** [comment]
@Koeng101 I'm thinking more about this - if the data just comes down to single / small files, do you think using storage might be overkill? Even the testing server has a 100GB filesystem - how many MTA files would really be needed to fill that up?

**Comment by vsoch** [comment]
We are actually okay storing the MTA files on the server. This can be re-addressed if that changes.
