### ISSUE TITLE
"Received" status (user generated)

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#130]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way for the end user to trigger that they have received a shipment. This can be as simple as a URL link that confirms that they have received the shipment and put it away properly. (eventually, we would like to include this as a QR code within each shipment, and to occasionally email the end users if they haven't scanned the QR code once the materials arrive).

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
Okay, since we removed the "Received" boolean, this would be best represented as a status of Received (to come after Shipped) for an order.status. It's not a completely accurate system (because a user would have to go out of their way to mark it) but it will work for now.

Since we are adding a listing of orders via #127, would it make sense to put a "Mark as Received" button there, in the case that the order was shipped?

**Comment by Koeng101** [comment]
That makes sense to me - just want to make sure there is also a URL that they could visit instead of directly pressing the button, so that they can just scan a QR code on their phones to affirm that they have received the parts.

**Comment by vsoch** [comment]
The issue with a quick way like that would be that we would need to check that they are the request.user that matches the user that created the order, and it would be unlikely that they would be logged in on their phone and thus the QR wouldn't work.

**Comment by Koeng101** [comment]
I'm imagining that the URL in particular doesn't do any user verification. Just if the URL is hit, the received status gets marked

**Comment by vsoch** [comment]
Are you sure about that? The order ids can be seen by any user, so in that the url only depends on that, anyone could maliciously change the status. What we would need to do is create a secret and then provide that secret url associated with the order. I'd recommend for this first pass just having the button in the user profile, as creating some kind of temporary URL warrants further discussion about how to do that, how to expire them, etc.

**Comment by vsoch** [comment]
okay here is how it's going to look, the user (if they own the order and the status is Shipped) will have the option to mark as received:

![image](https://user-images.githubusercontent.com/814322/68533348-7025f400-02f5-11ea-83b8-a2d3834fda78.png)


And then click to change to Received, and it's received!

![image](https://user-images.githubusercontent.com/814322/68533362-c2671500-02f5-11ea-9636-f12ef6fc01dd.png)

There is an associated url that could be converted to a code, but it's predictable as I mentioned above, so likely you'd want to change this to some system that can generate temporary urls to get around this.

```
http://127.0.0.1/o/shipment/mark-received/e8b20d28-5d17-4651-8ff8-4652f640067f
```
for the time being though, this should suffice for this issue! I'll push and update the server shortly.

**Comment by vsoch** [comment]
okay all set! https://github.com/vsoch/freegenes/commit/3a8756785f4bb9c876e12b1f22919383fb6da1d5 this will nicely fold into whatever future scheme you have for QR codes, etc.

**Comment by Koeng101** [comment]
Awesome! Thank works! Thanks so much
