### ISSUE TITLE
Number of parts in a distribution + link to parts

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#131]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to see the number of parts available in each distribution at first glance. This should just be in a column on https://freegenes.dev/c/catalog/distributions that gives a number of parts.

It would also be great if this then linked to a list of parts that are associated with that distribution.

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
The distributions page (local testing) has an added column for unique parts:

![image](https://user-images.githubusercontent.com/814322/68545168-7b7e2b80-0398-11ea-8192-b8f8263e9cd3.png)

It's a link, and clicking it will take you to a page with just the parts relevant for the distribution:

![image](https://user-images.githubusercontent.com/814322/68545245-3c040f00-0399-11ea-8678-1c74d3f48360.png)

**Comment by vsoch** [comment]
Closed with https://github.com/vsoch/freegenes/commit/6f6f036a824bbdcf0d43a2c884c2b2a99a499b6b
