### ISSUE TITLE
Download(CSV) to Plates(CSV)

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#132]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
There should be more clarity of what the CSV file is for a distribution, so a simple change of Download(CSV) to Plates(CSV) should do the trick (for example, here https://freegenes.dev/e/distribution/287d661f-05e3-4272-b545-cb1a4f2fc7f7)

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
Haha, I was worried about this too, I added a title attribute so a mouseover would provide more detail:

![Screenshot from 2019-11-10 09-09-22](https://user-images.githubusercontent.com/814322/68545319-ee3bd680-0399-11ea-8b64-d003b0ba5bb6.png)

But I like your solution better.

**Comment by vsoch** [comment]
![image](https://user-images.githubusercontent.com/814322/68545341-3955e980-039a-11ea-92ed-bd60e3abf2b6.png)

**Comment by marc4-stanford** [comment]
Shouldn't the label be "Plate Layout"?  

Is "Download a CSV with a single representative plate per plateset in the distribution"  the verbage that a naive user will understand?

I'm look at all of this from the point of view "What would Lauren think"?

/marc

**Comment by Koeng101** [comment]
Looking at it from the perspective of our target audience, they would likely have enough implicit knowledge to know what "Plates" meant. I personally like the simplicity rather than Plate Layout, and it is pretty clear what it'll mean.

**Comment by marc4-stanford** [comment]
The target audience is totally generic, not synthetic biology specific.  We have to make sure that the entire site works
for everyone that comes to see it.    Can’t assume any implicit knowledge.


/marc

--
Marc Fleischmann, Executive Administration, Special Operations and Strategic Services to Drew Endy & Christina Smolke
T: 650 245-4136

**Comment by vsoch** [comment]
I'm a good tester for this, I have little to no experience in Biology, and the contents of Plates (csv) meets my expectations to be a csv about the plates included. If you change it to Plate Layout, then I'm not really sure what that means.
