### ISSUE TITLE
More Plate CSV file export

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#135]
This extends #16 to include some fields needed to do "circular" import (allowing importing of exported plate).

Currently, `plate_name | plate_type | well_address | part_name | part_gene_id | sample_evidence | part_sequence ` are the headers when you export a plate from our system.

We would like for there to be a couple more headers for the following values:
```
Plate.plate_form

Well.media
Well.volume

Sample.status

Part.full_sequence
Part.optimized_sequence # replaces part_sequence, which I think is synthesized sequence right now.
Part.description
Part.authors
```

**Comment by vsoch** [comment]
Testing this out now locally...

**Comment by vsoch** [comment]
How is this?

[freegenes-distribution-openenzyme_1-2019-11-11.csv.txt](https://github.com/vsoch/freegenes/files/3832936/freegenes-distribution-openenzyme_1-2019-11-11.csv.txt)

I'm amazed at how some of the bio community prefers csv exports, I can barely view that file easily with vim!

**Comment by Koeng101** [comment]
Perfect, with one change:

`part_optimized_sequence` -> `part_sequence` (it is a bit confusing on a code side, but from a biology side, that is the part "sequence")

**Comment by vsoch** [comment]
Done! And closed with https://github.com/vsoch/freegenes/commit/e22df6ff4b5adc74713fadd8a7c3ebb1f9dccb99. Server is updated.
