### ISSUE TITLE
FreeGenes still on title page

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#136]
**Describe the bug**
When app is started, (or on live app, freegenes.dev), the landing page still has "FreeGenes" on it. 

**To Reproduce**
Visit freegenes.dev or start a local docker cotnainer

**Expected behavior**
For "FreeGenes" to be replaced with "Bionet Server".

It may be even better to have a more generic landing page that is configurable from wherever the app is deployed.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
How do you propose parsing that? Notice that there are two spans to handle the capitalization and coloring. We can't anticipate what the lab will have in advance, so either we have to hard code something or just remove the two toned colors.

**Comment by Koeng101** [comment]
I think easiest will removing two toned colors, even though it does fit FreeGenes quite nicely

**Comment by vsoch** [comment]
Which color would you like to keep?

**Comment by Koeng101** [comment]
The yellow, I think.

**Comment by vsoch** [comment]
I think I agree! Let me test this locally. I saw one more FreeGenes in the about too, I'll do another grep to check again.

**Comment by vsoch** [comment]
![image](https://user-images.githubusercontent.com/814322/68613506-e741c080-048c-11ea-9ac5-2b3402629047.png)

**Comment by Koeng101** [comment]
Awesome!

**Comment by vsoch** [comment]
All set https://github.com/vsoch/freegenes/commit/175816dd84fd639f0252d6d8100721d859801698
