### ISSUE TITLE
Unique constraint on Part.gene_id

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#138]
**Is your feature request related to a problem? Please describe.**
Multiple gene_ids doing funky stuff on local server.

**Describe the solution you'd like**
Enforce uniqueness on column gene_id in table Part

**Describe alternatives you've considered**

Anything else?

**Comment by Koeng101** [comment]
Specifically, messes with this chunk of code:

```    # Get plate names in advance. We are required to have all parts
    names = set([row[headers.index("Name")] for row in rows])
    existing = Part.objects.filter(gene_id__in=names).values_list('gene_id', flat=True)

    # We are required to have all parts represented
    if len(existing) != len(names):
        missing = abs(len(existing) - len(names))
        return "All parts are required for import: missing %s, import cancelled." % missing
```

**Comment by vsoch** [comment]
okay first I just want to verify we don't currently have any repeated gene_ids
```
gene_ids = [x.gene_id for x in Part.objects.all()]                                                                     

len(gene_ids)                                                                                                          
2991

len(set(gene_ids))                                                                                                     
2991
```

**Comment by Koeng101** [comment]
Nope, none in the system right now: Was just playing with a local copy to test out the plate imports, and accidentally imported a bunch of genes twice.

(I can see migrations might fail if there were extra copies of anything in our current server tho)

**Comment by vsoch** [comment]
Closed with https://github.com/vsoch/freegenes/commit/dcb1ee3793342e1c277643410298e07451f2f545

unique is enforced!

**Comment by vsoch** [comment]
yep that's exactly why I was checking first :)
