### ISSUE TITLE
Simplify Search / Make it more usable

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#139]
Attached is general picture of how I think https://freegenes.dev/search should optimally work.

In essence, all people really care about searching for are Parts (distributions are sufficiently small that one could just look through them manually). I've drawn in attached document the overall layout I'm imagining:

![image0](https://user-images.githubusercontent.com/2896607/68618391-0dac2f80-047e-11ea-835f-8455612b71d4.jpeg)

Basically, you can click a button to search available parts, or all parts (defaulting to available). There, there would be a few columns: `Name, Type, Tags, Available`. Underneath the name, similar to the current system, the `Description` of a Part is given. 

Since we're only searching parts, `Part : Gemini` would get verbose, so there is just `Gemini`.

One special part (that I don't know the difficulty of) is being able to use `#` to search tags on parts [this could be a feature for later].

You can click the `Available` section to be led to the `Distribution` that that `Part` is a part of.

This is a first pass version, which will likely take a couple iterations to get right, but I think it is a good start for most folks looking for parts.

**Comment by vsoch** [comment]
Is this just the front page, or site wide search?

I don't think we want to mess with (what is currently) the site wide search pages - that would make it almost impossible to find any other content you are looking for. What I see here to be a better solution would be to implement a new set of search functions / views, and specifically only for Parts. Then the question is - where would you like this to show up? How do we toggle between admin / staff vs not?

**Comment by vsoch** [comment]
And just to verify - you are also asking for a bunch of separate smaller menus / selectors _below_ the box. This looks like quite a bit of work, it might not be something I can do very quickly.

**Comment by Koeng101** [comment]
> What I see here to be a better solution would be to implement a new set of search functions / views, and specifically only for Parts.

That makes sense. In that case, we search should be hidden somewhere (maybe in a link from the Part search), since there is nearly nothing else that often needs searching for (the Map is pretty good for all physical objects).

> Then the question is - where would you like this to show up? How do we toggle between admin / staff vs not?

Probably where the current search shows up (current search is just a link to that page)

> And just to verify - you are also asking for a bunch of separate smaller menus / selectors below the box. This looks like quite a bit of work, it might not be something I can do very quickly.

Not looking for menus / selectors below the box, just columns with information. And understood that it might be tough! What are some of the harder parts? Perhaps we can make it easier by reducing some feature set, or by doing something else.

**Comment by vsoch** [comment]
What do you mean columns with information? What are the boxes / terms below the search box that point to the smiley face (is that part of the interface, or your annotations of a user interaction with it?)

**Comment by Koeng101** [comment]
I think that is just annotation. 

There are a couple of column names below the search box, and then for each row, there is some information. The boxes are just information in each row, I think. 

The smiley face just shows if something is available or not, and if it is, directs to the distribution it is part of.

**Comment by vsoch** [comment]
ohhh is that your drawing of a search result?

**Comment by Koeng101** [comment]
Yep!

**Comment by vsoch** [comment]
okay, all set https://github.com/vsoch/freegenes/commit/e1db37b40d0ebf511c57e2633b320dc12a230caa
