### ISSUE TITLE
Optimize Parts.available() to be efficient

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#142]
**Describe the bug**
When I do a blank search in the new search bar (https://freegenes.dev/search), I get a spinning wheel that results in no search result.

**To Reproduce**
Visit https://freegenes.dev/search and enter a blank search with the "Available Parts" parameter chosen.

**Expected behavior**
A list of all available parts to come up.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
lol, you found the edge case! I wouldn't expect an empty search to return all results, but in this case that would make sense here. I'll test locally now.

**Comment by vsoch** [comment]
Hmm, so I'm testing this out, and with the added filter to see if they are available (going through all parts) the gateway is timing out. I don't think that's going to work.

**Comment by Koeng101** [comment]
I'm guessing that it's probably because the query the ORM generates isn't too efficient or something, because it should definitely be able to get this information pretty quickly (it took a very short amount of time when I ran raw SQL to get this data off of last API). 

Is there a way to just make the queries more efficient?

**Comment by vsoch** [comment]
The function to determine if it's available isn't part of the database / ORM it's a custom function on the model. We could just disregard the available flag, but per your request to render this in the results table, having almost 3K results means that it would still time out. So given the constraints you've set, the only solution currently is to enforce the user to provide a query. When you can write some optimized SQL and update the available() function to use it, then we can remove that constraint.

**Comment by vsoch** [comment]
Updating issue - currently pressing enter on an empty box is not allowed, in the future it should return all results. This means:

 - optimizing the Part.available() function in the main models

The server will currently timeout (504) because the Part.available() function is not efficient to do this.

**Comment by Koeng101** [comment]
I actually think this is a pretty important feature to have, and at first glance doesn't seem THAT difficult to implement. 

```
# Search Function ##############################################################

def parts_query(q, available=False):
    '''search only across parts - we provide this search endpoint on the parts
       catalog page. If available is True, return only available parts.
    '''
    parts = Part.objects.filter(
                    Q(name__icontains=q) |
                    Q(description__icontains=q) |
                    Q(part_type__icontains=q) |
                    Q(gene_id__icontains=q)).distinct()

    if available:
        parts = [p for p in parts if p.available()]

    return parts
```
Can't the above `Part.objects.filter()` just be expanded optionally if available? Ie, a different filter is applied if available is `True`, which contains the ORM SQL logic necessary for an efficient search? Presumably, this has to be written down somewhere in order to do the p.available in the first place. 

In addition, couldn't there also be a pagination method so that all 3000 parts aren't brought up on one page at once?

**Comment by vsoch** [comment]
That's not where the issue is, the issue is with running p.available() (see the code for the function in the models/__init__.py file. And then using that same function to render the view in the table, since you asked to have this as a column.

**Comment by vsoch** [comment]
If you want to work on this, give a try to edit the part.available() function. That will fix both the view and the query function in search.

**Comment by Koeng101** [comment]
What does the capital Q mean? (I'm presuming lowercase q means the term to be queried)

**Comment by vsoch** [comment]
Correct! The little q is the query, the big Q is a special class provided by django to allow for conditional querying https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.Q

**Comment by vsoch** [comment]
okay this minimally will not timeout, it takes about six seconds: https://github.com/vsoch/freegenes/commit/2f5fb7407b9cf01cb98394561f7379f4c24f223c

You can leave this issue open if you want to take a look in the future for how to bring that down.

**Comment by Koeng101** [comment]
That's fine with me

**Comment by vsoch** [comment]
Also thanks for writing most of the query - I wouldn't have known how to do it easily, and this is the first time I've used raw (and it's really useful!)

**Comment by Koeng101** [comment]
Very welcome! I like writing most my SQL queries in raw because I feel like it is just clearer in what is going on than writing imperative python code for complex queries (simple things the ORM does better though)
