### ISSUE TITLE
After first order, pop up says 'You do not have an active order'

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#143]
**Describe the bug**
After I submitted my first order on Koeng102 (test account), I was redirected to https://freegenes.dev/o/ with a pop up that said 'You do not have an active order'. It also did not update the 'Date Ordered' column for the order that I did see (which is what I just placed).

**To Reproduce**
Order something on a new account on FreeGenes.dev

**Expected behavior**
A confirmation that my order was ordered, and for the Date Ordered column to be updated.

If applicable, add versions and screenshots to help explain your problem.
![2019-11-12-104234_3840x1080_scrot](https://user-images.githubusercontent.com/2896607/68700052-20d00580-0539-11ea-9392-eae29e5e82c3.png)

**Comment by vsoch** [comment]
The active order is for a cart, so once you submit, it's correct that you don't have an active order.  I'll update the text there.

For the date_ordered, that field has been used to indicate when the order is actually done (e.g., when the label is generated) and then date_shipped is when Hannah clicks "Mark as Shipped." If you'd like to change this standard we should probably check with @hverdonk first.

**Comment by Koeng101** [comment]
@hverdonk what do you think about updating the date_ordered column

**Comment by vsoch** [comment]
Also we have:

 - time_created
 - time_updated

which are auto populated for creation and update. The date_ordered is specific to creating the label, and date_shipped is for shipped.

**Comment by Koeng101** [comment]
But then `date_ordered` doesn't mean `date_ordered`, it means `date_label_generated`. I think from the user side, time_created makes much more sense, since they probably don't really care when the label is generated.

**Comment by vsoch** [comment]
If Hannah is ok with it, I agree that date_ordered more cleanly lines up with when the order was submit, and we should update the server to populate that field at this time.

**Comment by hverdonk** [comment]
I agree, we should change date_ordered to refer to the time when the user submits a request

**Comment by vsoch** [comment]
Thanks @hverdonk - I'll get this change in first thing tomorrow!

**Comment by vsoch** [comment]
okay! Just found the bug here - I implemented the function correctly, but used a hard coded string instead of the variable

```python
            # If a new status is requested, countersigned MTA letter has been uploaded
            if updated_status is not None:
                order.status = "Generating Label"
            order.save()
```

The function call for the admin view (note switches to Generating Label)

```python
        return _upload_mta(request, uuid, 
                           template='orders/upload-mta.html',
                           redirect_checkout=False,
                           updated_status="Generating label",
                           email_to=HELP_CONTACT_EMAIL)
```
and for the user, should switch _back_ to Awaiting Countersign

```python
    # In this case, if a user re-uploads an MTA (and it needs to again be
    # countersigned) we revert the status back to Awaiting Countersign
    return _upload_mta(request, uuid, updated_status="Awaiting Countersign")
```
so the fix was just honoring that variable!

```python
            # If a new status is requested, countersigned MTA letter has been uploaded
            if updated_status is not None:
                order.status = updated_status
            order.save()
```
We can definitely chock this one up to Vanessa brain fart / other slip in reality :) Will get changes in soon, along with updating the date_ordered.

**Comment by vsoch** [comment]
okay all set!
