### ISSUE TITLE
User and Institution to replace 'Notes' in Shipments Dashboard

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#144]
**Is your feature request related to a problem? Please describe.**
Yes, I'd like to be able to see who is ordering each object in our shipments view to determine if I want to reject their shipment or not.

**Describe the solution you'd like**
A column with 'User' and 'Institution'. This can replace notes, if need be.

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
Done.
