### ISSUE TITLE
Reason for rejection

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#145]
**Is your feature request related to a problem? Please describe.**
There is no reason for rejection - we should at least be able to tell someone why we rejected their order, so they can try again later.

**Describe the solution you'd like**
When you press the 'reject order' button, there is a view that lets you send a message to the end user on why their request was rejected

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
As a way to open up communication when a rejection happens, the user is sent an email (and can choose to respond to the bionode team) to ask for more detail. This is a better solution than a page they would need to look for proactively, as it is sent to them directly. Also, I added other notifications for shipped and marked as received (to the lab) https://github.com/vsoch/freegenes/commit/f3b36b3141a77f80594f5a20bf5a06ed8c4edb86.
