### ISSUE TITLE
Plate Import (generic)

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#147]
We would like to be able to import plates that came out of our system (in the form of Plate CSV files) directly into a different Bionet Node (perhaps a fresh node on your local machine). In order to do that, we need to take the output of one of our Plate exports ( https://freegenes.dev/download/distribution/csv/287d661f-05e3-4272-b545-cb1a4f2fc7f7 ) and have code that builds that plate into a different Bionet Node.

Unlike the Factory Import, we would be aiming to import Parts as well (I believe this was partially done for Factory Imports already). However, if a gene_id already exists within the system, skip that Part import (assume the one within the system is correct)

On a user side, just like with the Factory Input, users would need to input the container that the Plates will be going into.

**Comment by vsoch** [comment]
Could you please outline the fields from the export that you intend to go into the system? The only ones we currently export are name, plate_type, and plate_form, and there are many more that are needed to replicate a Plate model. In order for this to work (just for plates) we would need to also export (and then be able to import)

 - add an export of a length and height
 - export plate status
 - plate_vendor id
 - notes
 
Thaw count is specific to a lab so it doesn't need to be export (unless it's the actual plate you are sending over, in which case it should be known?) And as you said, container would need to be selected by the user. 

What about protocol?

The same exercise as above needs to be done with each of wells, samples, and parts, we only export a limited subset of fields there.

**Comment by vsoch** [comment]
I won't be working on this today so please take your time to carefully write out the spec.

**Comment by vsoch** [comment]
heyo! So I just ran this over my neurons again and have some thoughts! If we really want functionality to "export this actual plate from one node, import to another" I don't think the current export cuts it - we need to include not only the other fields, but also (ideally) the uuid, and that way we can have an absolute assertion that a plate already exists in a node, or another node for import. I think ideally what we would have is a json export of all flattened fields (across a plate down to whatever level of sample is desired) and then that will be very easy to import to another node.

Then the question is what does the (currently implemented) export actually serve to do? Is it an FYI here is the data about the plates you can use for some analysis, or is it's purpose to import to another node? If the first, then we should keep this simple export and have a second export intended for import. If the second, then the first export should be updated to be as I described.

Let me know your thoughts! I can work on this tomorrow morning.

**Comment by Koeng101** [comment]
I think a flat JSON file would actually be optimal for import / export capabilities! If we could get that implemented, then I think we're in pretty good shape (csv files later could just be adapted to make that JSON).

The currently implemented export is an FYI on data on plates for non-computer scientists. They will also probably want to import things from a spreadsheet ( where they currently store information about parts and such ), which is why I thought it might be easier to just use a spreadsheet in both directions.

**Comment by Koeng101** [comment]
(Was writing out a longer answer, but I think a JSON export and import would work just as well)

**Comment by vsoch** [comment]
okay I can give that a go - and to be clear, you want to export everything from Plate all the way down to well -> sample -> part? A few questions I'll ask while I have you:

 - Where would you like the button to export
 - What should the text be?
 - The import I'm guessing should be an import button under the factory actions?
 - Should we keep the previous export csv button?

**Comment by Koeng101** [comment]
> Where would you like the button to export

On the Plate Page (eventually, there should be support to do a JSON dump from a shipment, since plates should be linked there)

> What should the text be?

Export Bionet Packet

> The import I'm guessing should be an import button under the factory actions?

An "Import" button in the Inventory section (I think it should go in Factory actions, but I know other folks on team wouldn't agree to that)

> Should we keep the previous export csv button?

Definitely. I'm guessing nearly nobody will actually use the JSON export / import except people who have their own node. Vast majority of biologists just want to work in spreadsheets, which is why export and some type of import is important there.

**Comment by vsoch** [comment]
You got it! I'll work on this mañana por la mañana.
