### ISSUE TITLE
"Import Shippo Order" triggers a 404 error.

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#149]
**Describe the bug**
When I try to link a Shippo order to one of our shipments, it triggers a 404 error.

**To Reproduce**
On the "Actions" tab in the Factory, click "Import Shippo Order"

**Expected behavior**
Should allow me to input whatever is necessary to link a Shippo shipment to a shipment in our system.

**Comment by vsoch** [comment]
Are you sure you got a 404? I got a server error. Looking into it now!

**Comment by vsoch** [comment]
Can confirm now - you triggered server error:
```
uwsgi_1      | [pid: 32|app: 0|req: 1002/1795] 171.66.12.85 () {46 vars in 842 bytes} [Mon Nov 18 11:13:54 2019] GET /f/ => generated 16465 bytes in 8860 msecs (HTTP/1.1 200) 4 headers in 125 bytes (1 switches on core 3)
uwsgi_1      | Internal Server Error: /o/shipment/import-shippo-order
uwsgi_1      | Traceback (most recent call last):
uwsgi_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1      |     response = get_response(request)
uwsgi_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1      |     response = self.process_exception_by_middleware(e, request)
uwsgi_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1      |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
uwsgi_1      |     return view_func(request, *args, **kwargs)
uwsgi_1      |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
uwsgi_1      |     return self.dispatch(request, *args, **kwargs)
uwsgi_1      |   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
uwsgi_1      |     return handler(request, *args, **kwargs)
uwsgi_1      |   File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
uwsgi_1      |     if test_func(request.user):
uwsgi_1      | AttributeError: 'ImportShippoView' object has no attribute 'user'
```

**Comment by hverdonk** [comment]
Fair enough - my browser tab listed it as a 404, but it showed the server error page. I wasn't entirely sure which it was, so I put that it was a 404.

**Comment by vsoch** [comment]
No worries! I just need to make sure I am debugging the right one :)

**Comment by vsoch** [comment]
okay this should be fixed.

**Comment by hverdonk** [comment]
I uploaded a fake MTA (because it correctly wouldn't let me generate a shipment without one) and it succeeded, but when I clicked the "create shipment' button again, I triggered another server error.

**Comment by vsoch** [comment]
yep I see the error! I'm working on an API view now but I'll be able to look into this one after that.

**Comment by vsoch** [comment]
okay - so the reason this is happening is because you are trying to interact with an order that doesn't have a shipping address (it was a field you requested added after we verified it was okay with Stanford privacy). When you do have that metadata the address will be populated on the rendered page from it. This order doesn't have it, so the server errored, and what I'll add is a check so that it will just render an empty form instead.

For most orders here on out this shouldn't be an issue because the fields will be saved when the user submits, but for this small subset the fields are undefined. 

I'll have a fix pushed shortly.

**Comment by hverdonk** [comment]
Awesome, thank you!

**Comment by vsoch** [comment]
Should be all set now.
