### ISSUE TITLE
Pileup files return 500 when download attempt

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#15]
This is not urgent, but when I use the files download endpoint for any file that ends in pileup (not sure what these are!) it returns a 500 server error. I don't think I need these any time soon, and am just reporting the error for future notice.

**Comment by Koeng101** [comment]
These files were removed from the bucket when I moved all sequencing data to a separate service - they shouldn't be linked anywhere but the files. That was oversight on my part, but aren't necessary for migration.

**Comment by vsoch** [comment]
okay, in that case passing over them (a continue in the loop) should be sufficient. Thanks for the quick information!
