### ISSUE TITLE
"Create Shipment" triggers a 404 error

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#150]
**Describe the bug**
Similar to #149, selecting "Create Shipment" triggers a 404 error.

**To Reproduce**
On the [Dummy Order](https://freegenes.dev/o/details/d69dd1f0-24c5-4fb3-8e25-52a46598ba9e) (or on a different fake request that you create), click "Create Shipment"

**Expected behavior**
Should allow me to proceed to the label generation steps - entering addresses, selecting rates, etc.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
This was the same issue - the decorator added wasn't checking the request, and it was erroneous to add it!
