### ISSUE TITLE
Tag search searches all objects, now just the tag

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#151]
**Describe the bug**
When searching on hashtags, all parts come up, not just ones with the tag.

**To Reproduce**
https://freegenes.dev/search?q=#openenzyme

**Expected behavior**
Only for parts with the desired tag to appear

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
What is a search with a hashtag? Is there something you wanted implemented that I don't know about?

**Comment by vsoch** [comment]
I can add tags to be searched and remove any # characters, but custom parsing of the query string I think is out of scope for this round of work, because it's a much more complicated discussion and then implementation.
