### ISSUE TITLE
Final week line edits

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#153]
Now that most of the "Features" required are approximately done, we're on the final stretch of "line edits" (small improvements that shouldn't take much code itself). If any of these things will take a lot of effort, let's 86 it - each one of these things should mostly be removing some html elements or adding another link.

The basic idea is that we want going from Search -> Order to be very easy and obvious. Right now, there is no obvious way to go from searching to ordering without previous knowledge of the structure of the site. 

- [x] Add "Add to Cart" button on Distributions page itself
- [x] Add warning that searching all “available items” takes a little while
- [x] At bottom of each part, shows "Showing 1 to 6 of 6 entries". For example, https://freegenes.dev/e/part/40c81b4d-211a-481c-a369-6572bdd72cad . This is not very useful information for user, please remove
- [x] Left justify "Found X results" on search page
- [x] Allow "get" commands on API for all plates, wells, samples, parts, and collections
- [x] "Part: " on search page is redundant now that we are just showing parts, please remove
- [x] Instead of "yes" or "no" in available column on search page, have a "Get this Part" link if it is available. Instead of "No", have the column be blank
- [x] Change "FreeGenes" to "EndyLab" in config file to make sure that all references to FreeGenes are removed
- [x] Change "Available Parts" to "Available Physical Items" on search page and top bar
- [x] Remove "Status" from Parts.
- [x] Within search bar, instead of "Search FreeGenes Parts", include instructions for user, such as "Leave blank to search all items"
- [x] On Part Page, if part is available, have a "Get this Part" button
- [x] Default to "Available Physical Items" button on search is "On" instead of "Off"
- [x] Add square box around Globus on login page so it matches all other sites
- [x] Short explanation why users need to sign up with any of the current sites

We're going to meet again on Wednesday to get one more iteration in before meeting on Friday, so may add some things then (if that is alright)

**Comment by vsoch** [comment]
- plates, wells, samples, parts, and collections already have GET.

**Comment by Koeng101** [comment]
> Allow "get" commands on API for all plates, wells, samples, parts, and collections

My bad for not being clear, I should have said:

'Allow "get" commands on API for all plates, wells, samples, parts, and collections' for any unlogged user (completely open access)

**Comment by vsoch** [comment]
okay going to add some screenshots here to keep a record of changes (to be integrated)

Add to cart button added to distribution page (note that a regular user doesn't see the edit button, that's admin/staff only)
![image](https://user-images.githubusercontent.com/814322/69081005-4f972180-09fa-11ea-986b-e28f48de879b.png)

Warning about parts search
![image](https://user-images.githubusercontent.com/814322/69081194-b87e9980-09fa-11ea-98d7-baa44de3b3f5.png)

Removing 1 of 6 from part details view

![image](https://user-images.githubusercontent.com/814322/69081515-638f5300-09fb-11ea-97ae-216d93619fbc.png)

Gotcha on the permissions.

**Comment by vsoch** [comment]
@Koeng101 I've done all of the changes above, with two boxes left unchecked, details:

 - I removed the part.status from tables and import, but not from the model in the database because I don't want to risk the migration corrupting something. This is something that you can easily delete the fields from the model at a later point to do - there are too many moving parts (and I'm too anxious about an irreversible error) to do now.
 - Could you clarify how "Get this part" fits into the part page? If you are referring to the Part details page, that would be the page linked to from the search, so it wouldn't be logical to link to itself. The node doesn't have a way to order a single part, so it's not clear what we would link to here.

**Comment by Koeng101** [comment]
> I removed the part.status from tables and import, but not from the model in the database 

Sounds good

> Could you clarify how "Get this part" fits into the part page? If you are referring to the Part details page, that would be the page linked to from the search, so it wouldn't be logical to link to itself. The node doesn't have a way to order a single part, so it's not clear what we would link to here.

We just want there to be a link within the Part page to a distribution that you could actually get.

**Comment by vsoch** [comment]
Ah understood, then how about a link to each of the distributions the part is available in? It _should_ be the case that each part belongs to one, but we can't always be sure this will forever be true. What I'll do is add a Distributions row and then link (with the name of the distribution) to get it.

**Comment by Koeng101** [comment]
> Ah understood, then how about a link to each of the distributions the part is available in? 

Perfect!

**Comment by vsoch** [comment]
And this is going to be a pretty convoluted query to go from Part -> Sample -> Well -> Plate -> PlateSet -> Distribution, but it's only for one part so it shouldn't be terribly slow. This wouldn't work for a batch query.

**Comment by Koeng101** [comment]
I'm not sure if this is setup, but couldn't most of this stuff just be cached? Shouldn't be terribly slow if it's cached initially

**Comment by vsoch** [comment]
Django front end views would be cached I think.

**Comment by vsoch** [comment]
okay all set! Since we can check off the other two boxes, I'm going to close the issue.

Tomorrow I'm leaving for Supercomputing, so if you get issues in early (before 10:30am likely) I'll be able to work on them, otherwise I'll be back later evening / likely Wednesday.
