### ISSUE TITLE
404 Error on JSON plate export

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#155]
**Describe the bug**
I went to a random plate, for this example https://freegenes.dev/e/plate/544d7530-2cb6-46c2-8800-45253cf54f6c , and tried to export it as JSON, which triggered an error (https://freegenes.dev/export/plate/544d7530-2cb6-46c2-8800-45253cf54f6c) 

**To Reproduce**
Above

**Expected behavior**
A json file with the plate export

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
Just a missing import, and to verify, this is server error (500) and not 404.

**Comment by vsoch** [comment]
Fixed.
