### ISSUE TITLE
Associate Imported International Shipments With Existing Orders

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#157]
**Is your feature request related to a problem? Please describe.**
Importing a new international shipment creates a new order object in our database, rather than associating that shipment with the existing order that motivated the shipment in the first place. This divorces the relevant MTA from the package shipment information, and prevents customers from tracking their orders.

**Describe the solution you'd like**
When importing a Shippo Order, provide a dropdown menu of orders at the "Generate Label" stage to associate a shipment with.

**Describe alternatives you've considered**
I can't think of any, but I'm open to suggestions.

Anything else?

**Comment by vsoch** [comment]
The original design (as I understood it) would be to import the shipment as a new order, since it wouldn't exist. You are saying that your preference is to manually create an order (or have the customer / visitor do so via checking out a cart), and then require the import to select an existing order to overwrite?

**Comment by hverdonk** [comment]
Yes, if that is easily possible. We do not anticipate shipping many packages abroad, so if it's not a simple task, it can be worked around manually.

**Comment by vsoch** [comment]
Let me see what I can do! Working on it now.

**Comment by vsoch** [comment]
Since we are using an existing order, it doesn't make sense to require the user to enter a new name, so I'm going to remove that field. One less box to enter stuff!

**Comment by vsoch** [comment]
okay all set!

**Comment by hverdonk** [comment]
Woo! Thank you!
