### ISSUE TITLE
Importing shippo orders automatically assigns a date in the "Date Shipped" column

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#158]
**Describe the bug**
Newly imported Shippo orders are automatically assigned the current date & time as the "date shipped," rather than allowing the shipper to mark when the package has actually been shipped.

**To Reproduce**
Import the Shippo order associated with Ricardo Camilo Chavez Martinez, then look at the "Date Shipped" column. An existing example can be found [here](https://freegenes.dev/o/details/90e6ba01-3988-46d8-9429-6efe56ade62e)

**Expected behavior**
The "Mark Shipped" button should appear in the "Date Shipped" column.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
Ah okay, so right now I was grabbing the creation timestamps from the shipment object itself:

```python
                                         date_ordered=convert_time(shipment['object_created']),
                                         date_shipped=convert_time(shipment['shipment_date']),
```
would you like to keep the date_ordered (should be ok and correct I think?) and just clear the date_shipped (since the shipped field here is for when the lab does the shipment?)

**Comment by hverdonk** [comment]
yes, that would be preferable

**Comment by vsoch** [comment]
All set @hverdonk !
