### ISSUE TITLE
Add an "are you sure?" dialog box to the "Reset Shipment" button

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#159]
**Is your feature request related to a problem? Please describe.**
If someone accidentally clicks the "Reset Shipment" button, the shipment is immediately reset and the data is (as far as I know) completely lost.

**Describe the solution you'd like**
When the "Reset Shipment" button is clicked, a dialog box should appear asking a user if they are sure they want to reset the shipment. Doing so would prevent accidental resets.

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
I know the perfect thing for this! https://www.w3schools.com/jsref/met_win_confirm.asp

**Comment by vsoch** [comment]
![image](https://user-images.githubusercontent.com/814322/69196229-15f21380-0aeb-11ea-8eaf-a1f5f303b8cf.png)

**Comment by hverdonk** [comment]
That looks perfect! It didn't appear when I tested the reset on the dummy order, but from the way your version says "Bionet Server" I'm guessing you just haven't made the change live yet.

**Comment by vsoch** [comment]
You are correct! The above I was developing and previewing locally (working on other fixes before doing a server update). You should be good to see it now!
