### ISSUE TITLE
Plate CSV file export

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#16]
It was requested that we add a function to export a plate as a csv file (Quote is "Sometimes you Stanford types don't think about all of us computer illiterates out in the biological world, lol.") The headers would be

```Plate name, Plate type, Well Address, Part name, Part gene_id, Sample evidence, Part sequence```

Most of this info can be obtained from [/plates/recurse/{uuid}](https://api.freegenes.org/plates/recurse/addc09ef-0072-4649-a43b-148bc21522f7) but just need to be put in a convenient format for biologists

**Comment by vsoch** [comment]
Sounds reasonable to me!

**Comment by vsoch** [comment]
@Koeng101 is the request to be able to download:
 - a single plate?
 - a plate set?
 - all plates?

**Comment by vsoch** [comment]
I'll do (until I hear from you!)

 - a download csv button for the plate catalog page (meaning all plates)
 - a download csv button for a plateset page (for all plates in a plateset)

**Comment by vsoch** [comment]
ohhh there is a well address! So they really do want one plate :) okay, one plate it is!

**Comment by vsoch** [comment]
Which sequence do you want?
 - optimized
 - original
 - full
 - synthesized

I'll randomly choose synthesized for now, it's shorter than full :)

**Comment by vsoch** [comment]
okay, so they want something like the attached?  (I added the txt so it would be allowed for upload here, it doesn't download with that).

[freegenes-plate-2019-08-30-wells-42.csv.txt](https://github.com/vsoch/freegenes/files/3560919/freegenes-plate-2019-08-30-wells-42.csv.txt)

This is generated from a plate details page by clicking this button:

![image](https://user-images.githubusercontent.com/814322/64040317-c115b100-cb2a-11e9-81e3-8e221ff33b2b.png)

Are you sure labs don't want to be able to export platesets? And that they want csv?

**Comment by vsoch** [comment]
https://github.com/vsoch/freegenes/commit/da6a7e02106fde017ca378640d993529403e09be#diff-60d52fcdc600acda9ff21d8d0a0da474R68

**Comment by Koeng101** [comment]
1. A single plate or all plates from a distribution. Platesets are actually all basically the same, so the csv would download with just the UUIDs changed

2. Synthesized seems reasonable to me right now! If not synthesized, then full.

3. The attached file looks great to me! It also has information that some people actually requested, so I'll forward it to some folks :)

**Comment by vsoch** [comment]
okay, both download csv for platesets and distributions are also added! https://github.com/vsoch/freegenes/commit/8df4d4559714343efaccc9959e8683177fbd3394#diff-60d52fcdc600acda9ff21d8d0a0da474L105
