### ISSUE TITLE
Another round of search results improvements

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#160]
Some more line edits from a conversation we had today:

## General edits

- [x] On homepage (freegenes.dev), remove checkbox (defaults to only searching available parts)
- [x] Remove yellow warning on + Search all X on search page (yes, I know this was just asked for, but in review it didn't look as nice to folks so it was asked to be removed)
- [x] Instead of "Search EndyLab Parts", rename to "Search Items"
- [x] Search button on the right is a little too low
- [x] Description on Parts/Items should be left justified

## First page search results

Generally, we want there to be a couple things that are very available within the first page of the search results. 

- Name
- Description
- Tags
- Type
- Terms and conditions
- BSL
- Availability

Terms and conditions + BSL (biosafety level) are things which are assumed within the FreeGenes system, and can be assumed generally, but still need to be there. Fortunately, nothing in the system has to have special modification. Within Distributions, there needs to be a "terms" column within the database with two possible values: UBMTA and OpenMTA. Everything we have right now is OpenMTA, and that can be defaulted. Within every Part, there also needs to be a BSL level, which are 1-4. Again, everything in the system is just BSL1.

- [ ] Add Biosafety Levels to search results
- [ ] Add Terms to search results (if available)

## Second page search results

When you actually click on any of the Parts, and a second page is brought up, we want additional information:

- Sequence
- Author

- [x] Remove 'Status' 
- [x] Add Author
- [x] Add Sequence (optimized sequence)

Few more edits tomorrow - discussing harder to implement stuff with group. Cheers

**Comment by vsoch** [comment]
working on this now! I made it back alive from SC! It was _so fun!_

**Comment by vsoch** [comment]
For the biosafety and terms, this is totally new discussion and out of scope, so I'd recommend opening a new issue for a future todo.

**Comment by vsoch** [comment]
These are all set! I've opened #161 to address the levels and terms future addition.
