### ISSUE TITLE
Our shipment's status doesn't update when an international shippo shipment is attached to it

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#162]
**Describe the bug**
When I import an international shipment and attach it to an existing order, the status of that order doesn't update, nor does it provide a button to mark the order as shipped.

**To Reproduce**
Create a new order and attach an international shipment to it (the one to Ricardo is the one I used). Then, check the order's status.

**Expected behavior**
The status should change to "Label Generated" and the option to "mark shipped" should be present.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
hmm that's not logical, it's definitely added:

```
            # Update the order
            order.user = self.request.user
            order.date_ordered = convert_time(shipment['object_created'])
            order.status = "Generating Label"
            order.label = label
            order.transaction = {"eta": None}
```
Can you point me to this order to look at?

**Comment by hverdonk** [comment]
Sure. It's this one: https://freegenes.dev/o/details/4033dea9-490f-48a6-805c-1ed607aa3f39

**Comment by vsoch** [comment]
Also we don't have a "Label Generated" status, we have "Generating Label." I think if you want to say it's generated, the next one is "Waiting to Ship" ?

**Comment by hverdonk** [comment]
Yep, that's what I meant ha ha

**Comment by vsoch** [comment]
okay let me change the status then, that might just be the issue.

**Comment by hverdonk** [comment]
Most likely. Thanks!

**Comment by vsoch** [comment]
okay updated - all look good now?

**Comment by hverdonk** [comment]
perfect, thank you!
