### ISSUE TITLE
List only "Processing" orders in the "Import Shippo Order" page [LOW PRIORITY]

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#163]
**Is your feature request related to a problem? Please describe.**
When selecting an order to attach a Shippo shipment to, I'd like for the page to list only processing orders so I don't accidentally overwrite an existing completed order.

**Describe the solution you'd like**
Filter out the orders listed as (Completed) or (Shipped).

**Describe alternatives you've considered**
I know Keoni has requested several other features, and those absolutely take priority over this one.

**Comment by vsoch** [comment]
We would probably want to filter down to:

 - Awaiting Countersign
 - Generating Label

?

**Comment by vsoch** [comment]
All set.

**Comment by hverdonk** [comment]
Thank you!
