### ISSUE TITLE
Next round of Search Improvements

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#164]
# Line edits
## On Homepage

- [x] Replace "Search Parts" in searchbar with "Search Items"
- [x] In upper left corner, add "Bionet Server" to name, so for example, freegenes.dev would be "EndyLab Bionet Server"
- [x] Remove large middle yellow "EndyLab" and have just "What are you looking for"
- [x] Replace "Collaborative, Open Source, Governance" with "Organize, Share, Create". The text underneath can just be lorem ipsum, we can add that later as docs
- [x] Instead of "What is EndyLab", have "What is a Bionet Server"
- [x] Browse EndyLab button at bottom goes away

## On Search page

- [x] Remove or hide "Search all EndyLab" (or make button only viewable by admins, since normal folks don't really need to search that anyway)
- [x] Description should be in the same box as what is describing (for example, https://freegenes.dev/search?q=popen_v3&availableParts=on)
- [x] Add Biosafety level (BSL1 for everything right now). This is desired from the perspective of setting expectations for outside parties concerned about safety (and has actually appeared as a concern in known newspapers when talking about the project)

## On Parts page

- [x] Remove "Part :" at top 
- [x] Remove Samples button from the view of normal users
- [x] Line break the sequences so they fit on the page nicely\

## On Distributions page

-  [x] Add Terms that Distributions are available under. This shouldn't be too hard of a change, and is extremely relevant to what the BioBricks Foundation is trying to accomplish (making OpenMTA a general thing)

**Comment by vsoch** [comment]
I don't know what "Add Terms that Distributions are Available Under" means, please write out the changes you would like.

**Comment by Koeng101** [comment]
In the `Distributions` object, there is a column called "terms". It can have 1 of 2 values, OpenMTA and UBMTA. Everything we have is OpenMTA, and it can be defaulted / only changed in admin.

**Comment by Koeng101** [comment]
(In the future there could probably be more which is why it is not a boolean)

**Comment by vsoch** [comment]
Distribution does not have a field called terms.

**Comment by Koeng101** [comment]
That would need to be added in the models. It seems like a simple thing to add, is there some roadblock there that I should know about?

**Comment by vsoch** [comment]
No, but I need you to be specific about these details if you want me to implement them :)

What is the default?

**Comment by Koeng101** [comment]
OpenMTA is the default (sorry for being unclear with "it")

Basically, we want some way to present a distribution as under the OpenMTA or UBMTA, since that has been a big problem Addgene has been trying to solve for well over a year now.
