### ISSUE TITLE
Line edits before meeting

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#165]
- [x] Change "Available" column on search page to "Get this item"
- [x] Change "Get this part" to "Add distribution to cart
- [x] Description for a Part on the search page should not be hyperlinked with the name of the part
- [x] "Key" and "Value" on Parts page is unnecessary: please remove
- [x] On homepage, instead of "What is a Bionet Server?" have "What is the Bionet?"
- [x] Instead of "Distribution" on Parts page, have the label "Get this Part". Also have "Get this Part" bolded and at the top of the key,value list.

**Comment by vsoch** [comment]
And just to confirm - "Get this part" used to link to the distribution page, and now it will just add the distribution to the user's cart, if it isn't already there. If it's already there, the button is disabled.
