### ISSUE TITLE
New requests don't have "date ordered" automatically attached

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#167]
**Describe the bug**
When a user creates a new order, there is no "date ordered" associated with it.

**To Reproduce**
Create a new order through the freegenes.dev site, appending a fake MTA. Then, view that order in the Shipments dashboard.

**Expected behavior**
The date that the order was submitted should populate the "date ordered" field.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
This is also done in that same POST checkout function (as discussed in #166) 

```python
                # When the order is checked out, update status to awaiting countersign
                order.status = "Awaiting Countersign"
                order.date_ordered = timezone.now()
                order.lab_address = lab_address
                order.shipping_address = shipping_address
                order.save()
```
so I'm wondering if that function isn't being triggered...

**Comment by vsoch** [comment]
This should be resolved here - https://github.com/vsoch/freegenes/issues/166#issuecomment-557688061 the change of status was triggering the cart to not be found, and checkout to be skipped entirely.

**Comment by vsoch** [comment]
This was the bug mentioned above, now fixed.
