### ISSUE TITLE
final-final line edits

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#168]
- [x] On search and distributions catalog, if you are not logged in, add a note that says "You must be logged in to order any materials"
- [x] On any given Distribution page, remove "Distribution :"
- [x] Have "Get this item" be rightmost column

**Comment by vsoch** [comment]
All set! https://github.com/vsoch/freegenes/commit/9dbdc49f59ce6da10ea3d62549fa7386eacd4375
