### ISSUE TITLE
Possibly Missing Data for Migration

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#17]
Here I'll keep a list of TODOs, or missing information for migration, etc.

 - Plates should have breadcrumb and/or notes (missing)
 - Evidence for samples is usually None, so it cannot be required
 - ip_check_ref is blank (Part) so it cannot be required
 - outside collaborator status for samples
 - no schemas, plans, or operations are exported from the API
 - for now I'm removing the user requirement for orders, because we have address links (not users)

And shipment, parcel, and address will be represented elsewhere, linked to a user. This is going to remain a TODO until we have more of the application developed and can better develop this.

**Comment by vsoch** [comment]
- There are plates defined with protocol uuids that don't exist, so protocol cannot be required for a plate

**Comment by Koeng101** [comment]
1. Plates shouldn't have breadcrumbs, but they are required to have a container uuid. You can use container object to build a breadcrumb.
2. I'm guessing that in the cases that the evidence is None, the status is also None. If there is a status, it should have some evidence behind it.
3. ip_check_ref isn't required. We need some more software to begin annotating that part (basically setting up a separate BLAST database)
4. As discussed I presume
5. Correct, I was developing those locally when you had joined the team so I stopped their development to work on other things
6. Good idea, though we do have those user uuids coordinated to different people, so eventually when they make accounts we can go back and link these previous orders to them.
7. Sometimes plates are build manually, in which case they do not have protocol uuids

**Comment by Koeng101** [comment]
8. I will need to go back and fill in all the part descriptions, they should be required (perhaps just put placeholder?)

**Comment by vsoch** [comment]
ah okay! 

## Plates and Breadcrumbs

So for plates I'll remove the field and add a breadcrumb property that returns a list of the containers:

```python
    @property
    def breadcrumb(self):
        '''a breadcrumb is a trace of the plate up to the parent container.
           we start at the child and trace up to the parent, so the order
           is first child to parent, and we reverse to give user parent
           to child.
        '''
        breadcrumb = []
        container = self.container
        while container:
            breadcrumb.append(container.name)
            container = container.parent

        # Reverse, give to user parent to child
        breadcrumb = plate.breadcrumb[::-1]
        return breadcrumb

```
This makes sense because it's a fairly dynamic thing - we don't want to be updating the field, but generating from the structure that actually exists. Here are some examples:

```python
In [2]: for plate in Plate.objects.all(): 
   ...:     print(plate.breadcrumb) 
   ...:                                                                                                                                                
['ShadowRealm']
['EndyLab', 'FreezerHall', 'FearlessWanderer', 'Shelf_4', 'Rack_2']
['EndyLab', 'FreezerHall', 'XpertCommander', 'Shelf_4', 'FreeGenes_Rack_A']
['EndyLab', 'FreezerHall', 'XpertCommander', 'Shelf_4', 'FreeGenes_Rack_C']
['EndyLab', 'LabHall', 'Trp', 'KG_Bench']
['EndyLab', 'FreezerHall', 'FearlessWanderer', 'Shelf_4', 'Rack_2']
```

Agreed, we can link users when a deployment is ready. I'll add a placeholder for parts - thanks for the speedy update, hope you enjoyed Boston! I'm almost done with the API after this weekend, I'll send you an update probably later today.
