### ISSUE TITLE
User Interface Views

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#18]
I'm putting together a list of TODOs based on the user stories, other discussion, and general intuition. Likely this will keep me busy for the remainder of the week into next week.

 - [x] general search interface (https://vsoch.github.io/freegenes/docs/usage/interface#search). This is accessible from the site main page (the search box "What are you looking for?) along with the search endpoint at /search). 
 - [x] add search bar / icon to navigation for all pages
 - [x] browse by type (akin to http://parts.igem.org/Catalog) (done for Collections, Distributions, PlateSets, Parts)
 - [x] all entities need details views (e.g., when the user clicks on a particular part, they need to see it.) Given that each has different fields, needs, custom views based on logged in / not, admin vs. user, this will take a bulk of time (these are mostly done).
 - [x] lab technician (staff) "find what I'm looking for" views, these [user stories](https://vsoch.github.io/freegenes/docs/development/user-stories#the-lab-technician)
    - [x] map view for entire lab, along with containers
    - [x] get samples available for part, and go to location to get 
    - [x] link to locate a specific plate from a plate page (to the highlighted lab map)
 - [x] authenticated user (after search) should be able to [add to cart](https://vsoch.github.io/freegenes/docs/development/user-stories#ordering) and checkout would coincide with checking for MTA, etc., and generating an order. (more on this when I get to it).
   - [x] checkout view redirects to sign-mta form
   - [x] mta form allows user to download and upload 
   - [x] checkout view changes order status, submits email
 - [x] shipping (staff) need these [views](https://vsoch.github.io/freegenes/docs/development/user-stories#shipping). Still need to interact with shippo API.
 - [x] current orders I think will be best viewed in the admin interface. We can re-assess if it needs customization (easy to do).
 - [x] all detail views should had edit button to admin interface (for super user only)
 - [x] dashboard page has stats/metrics, and an orders page (all orders for admin, or just user orders for user)

Some of the above for entry will work with admin views, other will need customization. And related (but not a point in this issue) we'll need to add search functionality for sequences based on decision / feedback in #11

And various random points:
 - any entity that *can* be ordered needs an "add to cart" button for logged in users
 - Anything that has a QR code needs to show the proper urls to give to the printer after entities are added (just plates?)

I'll update this issue as I make progress.

**Comment by vsoch** [comment]
Quick documentation update - I added a [page](https://vsoch.github.io/freegenes/docs/development/views) that will overview organization of files, along with naming of templates and urls. It's some of that random stuff that lives in my head that I can't assume someone else can read minds or just figure out :P

**Comment by Koeng101** [comment]
## Answers
1. An author can be a user, but does not have to be. I imagine authors are basically just orcid id links (https://orcid.org/), while users can actually do things.
2. Sure, we can go over that. For now, feel free to expose everything except personal information (shipments, etc). All of those fields are open on the API right now, and it doesn't hurt to make them open when we migrate the database before making some more secret

**Comment by vsoch** [comment]
woot, I made a label! 
![image](https://user-images.githubusercontent.com/814322/64028843-63289f80-cb11-11e9-9467-f34260a828ee.png)

This API is pretty neat :)

**Comment by vsoch** [comment]
The shippo views are done! https://vsoch.github.io/freegenes/docs/usage/interface#shipments

What isn't implemented is coordination between some plate scanner and our interface - this is a more advanced feature that we can discuss further. It seems like we'd need some way to program the scanning device too, and then have it check against some API point to compare the plate IDs with what is detailed in the shipment.
