### ISSUE TITLE
Use jExcel for sheets

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#2]
https://bossanova.uk/jexcel/v3/

**Comment by Koeng101** [comment]
looks awesome to me for the job board

**Comment by vsoch** [comment]
@Koeng101 could you give more detail about what you'd want for the job board? Currently, the dashboard shows staff/admin an interactive table with all orders. Do we need any of that content editable (to warrant jexcel?) I was thinking this would be good for something that needs to act like a spreadsheet in the browser (click and edit).

**Comment by vsoch** [comment]
We are largely using datatables for tabular data, and I don't see an (immediate use case) for Jexcel, so closing issue. And if we were to need this, I've since tried this out and my preference is still for handsontable!
