### ISSUE TITLE
Part descriptions get cut off without a way to expand

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#31]
**Describe the bug**
Part descriptions, when you click on parts themselves, are shrunk with a "..." with no way to expand

**To Reproduce**
Visit https://freegenes.dev/e/part/8ac90b7c-7c0c-4268-a56f-4445cd5387ac

**Expected behavior**
I would like to see the full description

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
Definitely! Are the descriptions small enough so that they should stay in the field of the table? If so, I can render the whole thing. If not, we can have some special section.

**Comment by Koeng101** [comment]
Hopefully, they'd be much larger than the field! In the optimal case, they'd be able to look like this - http://parts.igem.org/Part:BBa_K914003

(though I understand adding pictures right now may be out of scope)

**Comment by vsoch** [comment]
okay - removed the limit! Until we actually have long descriptions, let's keep rendering in the table.
