### ISSUE TITLE
Toggle Admin Mode

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#32]
**Is your feature request related to a problem? Please describe.**
When browsing the website or doing an order, I'd like to see what a normal user would see, not what an admin could see.

**Describe the solution you'd like**
A toggle switch to be able to view things as a normal user, or a login system where I could use something else to login (since I only have 1 github)

**Describe alternatives you've considered**
Creating a different account somehow

Anything else?

**Comment by vsoch** [comment]
I think the easiest thing to do would be to just login as a user without admin. The permissions are a globally set thing for a specific user - so creating this "toggle" for the same account is challenging to do (and not a good idea for implementation).

**Comment by Koeng101** [comment]
Awesome - should I create a separate account without admin?

**Comment by vsoch** [comment]
Yes, I think that's most straight forward!

Facebook has a "view as this other person" feature, and they had to take it offline (maybe sometime last year) because it led to a huge security issue. I'm definitely not wanting to try to implement something similar, because simpler authentication systems / views tend to be better.

**Comment by Koeng101** [comment]
#37 would be relevant here, since I can pretty much only login with my github account.

**Comment by vsoch** [comment]
I think for this issue what we really need (and Drew is expecting) is a different looking portal for the actions of the lab, period. The user facing front end views will continue to have variations for logged in lab staff vs. everyone else, but won't be the primary dashboard for the lab.

**Comment by vsoch** [comment]
The site is broken into the various portals, each associated with a different set of permissions.
