### ISSUE TITLE
Phone number with order

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#33]
**Is your feature request related to a problem? Please describe.**
To ship something with Fedex, we need the phone number of the recipient.

**Describe the solution you'd like**
A mandatory section during ordering for phone numbers.

**Describe alternatives you've considered**
Using a different shipper - however, we get a really really good deal with Fedex and they ship internationally quite well.

Anything else?

**Comment by vsoch** [comment]
okay will add this asap!

**Comment by vsoch** [comment]
And just to confirm - still using Shippo, but creating a Fedex shipment.

**Comment by Koeng101** [comment]
Yes, trying to work out a way to continue using Shippo that works within Stanford's system

**Comment by vsoch** [comment]
We'll need to talk about this - the charge code (or similar) for the PI should not be kept with Shippo.

**Comment by vsoch** [comment]
All set, phone is added! https://github.com/vsoch/freegenes/commit/ef28a00fc797cdaac2587e6bf75bd203abbdd220
