### ISSUE TITLE
Plate CSV downloads give blank CSV files

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#35]
**Describe the bug**
When I try to download a csv file of a plate, the csv file is completely blank

**To Reproduce**
Visit https://freegenes.dev/e/plate/c4735458-f649-4ba2-b25d-5210d9246d26 and click "Download(CSV)".

**Expected behavior**
A csv full of information regarding what is in the plate

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
There's nothing to download for that plate - it doesn't have any wells. What I'll do is disable the button.

**Comment by vsoch** [comment]
okay - I made showing the button conditional on having wells, and also added a field for the number of wells to the plate.
