### ISSUE TITLE
Previous shipments need to be added

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#36]
**Is your feature request related to a problem? Please describe.**
In previous orders, such as https://freegenes.dev/o/details/3b67f449-916f-4981-9f0f-a842d490b3b6 ,  there isn't a link to it's shipment

**Describe the solution you'd like**
A link to the shipment page on the order page, available to admins and to the user who placed the order

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
Have you created it yet? Once it's created, the "Create Shipment" should change to just link to a record of it.

**Comment by Koeng101** [comment]
Oh, I have not. I was just confused about previous shipments that may need to be imported in (or should we just manually migrate them? Since there are a small quantity of them)

**Comment by vsoch** [comment]
Oh, yes if there is an order in the system that has a previous shipment, the reason it's not there is mostly because I couldn't export that data from the API. If you want to send me dumps of what is missing, I can easily add.

**Comment by vsoch** [comment]
Actually just kidding, I do have shipment exports! I just didn't add them because I forgot about them.

**Comment by vsoch** [comment]
Working on this now! Apologies for my oversight. I'll add the data to the import script, test locally first, and update the issue when it's finished.

**Comment by vsoch** [comment]
hey so I'm not going to be able to get any information for previous shipments with a test token - it either is the case that the test token doesn't work to retrieve actual transactions, OR that transactions that are completed can no longer retrieve labels. I would need to test with an actual token to confirm which of the above is the case.

In the case that we cannot retrieve previous information, I could add the transaction ids from the previous orders, but that wouldn't produce a link to a label or a tracking object. Let me know what you'd like to do.

**Comment by vsoch** [comment]
For an example, say I've read in a previous Shipment from the api, I can get a transaction id and then try to retrieve the label (which has the link to print / track):

```python
import shippo
from fg.settings import SHIPPO_TOKEN

# ... read in shipments
for shipment in shipments:
    # 1. look up order based on uuid (not shown, order is found)

    # 2. retrieve transaction based on it 
    label = shippo.Transaction.retrieve(shipment['object_id'], 
                                                            api_key=SHIPPO_TOKEN)
```
The above returns 

```
InvalidRequestError: {"detail": "Not found"}
```
I (hope) because it's a test token, but I can't be sure.

**Comment by Koeng101** [comment]
Sent real token for testing.

**Comment by vsoch** [comment]
Got it! Thank you, I'll try again!

**Comment by vsoch** [comment]
Just following up here - using the live shippo token, I was able to retrieve previous labels, and update the orders in the current database. This means that their status (given a label) is now complete, and that you can see the link to track (not always available, I suppose FedEx purges after some time?) and for the label.
