### ISSUE TITLE
Logins other than Github

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#37]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be good for login options other than Github, due to many biologists (and many of our end users) not having a github account

**Describe alternatives you've considered**
Logins other than Github - perhaps Google or similar

Anything else?

**Comment by vsoch** [comment]
Take your pick!

 - via plugins: https://vsoch.github.io/freegenes/docs/plugins/
 - other social auth:  https://vsoch.github.io/freegenes/docs/development/setup#authentication-secrets

And we can support potentially any from Python Social Auth (they are called backends) https://python-social-auth.readthedocs.io/en/latest/backends/

The limit is on the user email - so you can't register one account on GitHub that uses the same email for Google, for example.

I would recommend something that a lot of users are likely to have such as Google login. Let me know what you decide.

**Comment by vsoch** [comment]
Just to update the issue - I tried Google and it would only work for @stanford.edu (so I disabled it). I enabled Twitter, since lots of scientists tend to be on there.

**Comment by vsoch** [comment]
We've added Google and Twitter, so closing this for now! If there are requests for additional logins, we can re-address.
