### ISSUE TITLE
Models Questions

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#4]
- What are options for Parts -> status?

Specifically, I'd like to have verbosely written statements to describe each of:

```python
PARTS_STATUS = [
    ('null', 'null'),
    ('optimized', 'optimized'),
    ('fixed','fixed'),
    ('sites_applied', 'sites_applied'),
    ('syn_checked', 'syn_checked'),
    ('syn_checked_failed', 'syn_checked_failed')
]
```

And for Part Type also - what are the descriptors for each of these?

```python
    PART_TYPE = [
        ('full_promoter', 'full_promoter'),
        ('promoter', 'promoter'),  
        ('rbs', 'rbs'),  
        ('cds', 'cds'),
        ('vector', 'vector'),
        ('partial_seq', 'partial_seq'),
        ('linear_dna', 'linear_dna'),
        ('plasmid', 'plasmid'),
        ('terminator', 'terminator'),    
    ]
```
What is the difference between promoter / full promoter?

**Comment by Koeng101** [comment]
Will do a push later for part_status.

The two part types mainly distinguish if the promoter comes or doesn't come with a ribosomal binding sequence (rbs). Eukaryotes don't really have ribosomal binding sites, so they almost always use full_promoter. 

full_promoter = promoter+rbs

In the physical world, these are cut site definitions of moclo https://www.addgene.org/cloning/moclo/

**Comment by vsoch** [comment]
Understood! This issue is represented with #1, so closing here.
