### ISSUE TITLE
Search test in Mac Browser

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#40]
Hey @Koeng101 I just tested search (without being authenticated) and it worked okay - so yesterday when it didn't work for you that might have been a bug with the browser. Could you try again, and then open the JavaScript console to see if there are any errors?  It also could have been something about Marc's browser (e.g., adblocker or similar).

**Comment by Koeng101** [comment]
Works on my browser. Will try with Marc's on wednesday

**Comment by vsoch** [comment]
I'm assuming that everything worked ok, since this is 27 days old? Closing issue, please re-open if there is a regression.
