### ISSUE TITLE
Tag view on catalog doesn't work

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#45]
**Describe the bug**
When I visit https://freegenes.dev/e/tag/e555c579-3c66-4642-a426-c4362a5e4833/parts/ (from https://freegenes.dev/c/catalog/tags) I get a 404 error

**To Reproduce**
Visit the site above

**Expected behavior**
A view of the parts associated with a tag

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
That's embarrassing, I just forgot to implement it :) Working on it now!

**Comment by Koeng101** [comment]
Many eyes make bugs shallow! Got a lot of these from getting other people to look over site.

**Comment by vsoch** [comment]
okay these are all fixed! Sorry for the oversight! It must have fallen off my mental queue :)
