### ISSUE TITLE
Autogenerate dates on the OpenMTA PDFs

### ISSUE THREAD

**Issue by eyesmo** [vsoch/freegenes#47]
I think for records-keeping purposes, it would be good if the filename of the PDF generated when filling out the OpenMTA form automatically included the date when the file was generated, in YEARMMDD format.

**Comment by vsoch** [comment]
Oh that's a great idea! Definitely will add this.

**Comment by vsoch** [comment]
So it's more clear, does YYYY-MM-DD work? (note the dashes)

**Comment by eyesmo** [comment]
Yep, that'll work great!

**Comment by vsoch** [comment]
All set https://github.com/vsoch/freegenes/commit/cca553eb45b42248cbcf441338a4ac5e0161a57d
