### ISSUE TITLE
OpenMTA web form

### ISSUE THREAD

**Issue by eyesmo** [vsoch/freegenes#48]
At the moment, I can only fill out Recipient Organization name and address, and Recipient Scientist name and title before downloading the web form as a PDF. Is that intentional? I feel like being able to fill out at least the Additional Information box, as well as the Printed Name, Title and Date for the recipient at the bottom would streamline things.

Also, at the very bottom after the button for uploading the MTA PDF file, the form asks for '*Institution.' Is this supposed to be the institution the recipient is associated with, or provider is associated with? Would be good to just add an extra word to clarify.

**Comment by Koeng101** [comment]
(Recipient association, good catch!)

**Comment by vsoch** [comment]
My understanding (and from what I can see in the examples that are filled out) is that the receiving lab is supposed to fill that out. The signing user wouldn't know what to put.

**Comment by vsoch** [comment]
I intuited being on the left side of the form meant it was for the lab to fill out - what exactly is "Additional information" for then?

**Comment by vsoch** [comment]
What institution would it be other than the one you are signing on behalf of ? :thinking:

**Comment by eyesmo** [comment]
The institution you're requesting the sample from?

**Comment by vsoch** [comment]
I wouldn't think of that, but it's a good point that someone might. :fearful: 

https://github.com/vsoch/freegenes/commit/16a9fd3cbb4b356950929ffe77229af251eac538
https://github.com/vsoch/freegenes/commit/7efd39af820551619467a97f645c7ccd1fbc5a2d

Done.
