### ISSUE TITLE
MTA web form activation email

### ISSUE THREAD

**Issue by eyesmo** [vsoch/freegenes#49]
Looks like using the MTA web form for the first time requires email activation/authentication. However, it's been several (5?) minutes since I clicked to send the activation email, and I haven't received it yet. It's not in junk/spam either. This comes after logging in from Twitter.

**Comment by vsoch** [comment]
That's because Keoni needs to respond to it, not you.

**Comment by vsoch** [comment]
@Koeng101

**Comment by Koeng101** [comment]
Where do I do that?

**Comment by vsoch** [comment]
It's now associated with the email for the lab (it was previously mine) so wherever / whomever that goes to, he/she needs to click a confirmation link (and then the form will come in to the same email).

**Comment by vsoch** [comment]
This has been resolved, thanks again for the report @eyesmo. Closing.
