### ISSUE TITLE
Streamlining Outgoing Orders

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#56]
**Is your feature request related to a problem? Please describe.**
A few quick "nice to have" features that would make shipping a bit easier. Surfaced while working on #52 but not critical to fixing that issue.

**Describe the solution you'd like**
- Adding a date field to the Outgoing Orders chart, so I know when they were created without having to click on the order.
- Reverse the sort order so more recent orders appear on the first page. This will help as we get more and more orders, so I don't have to click all the way to the last page.
- Expose shipper phone number field and PTA field to the user. PTA should **not** be a required field.

**Describe alternatives you've considered**
The first two are just for convenience. I can already reach the information I need in the current system. A "last page" button would also work in place of reversing the sort.

The third solution is important because other adopters who use this software to ship their own goods will need to input their own information. I doubt all of the implementers have technical experience, so it would be easier for them to have a little box in the "create a shipment" form to put the information in, rather than to enter the code and change it manually.

**Comment by vsoch** [comment]
@hverdonk I can work on these! For the third point - right now we are assuming that the shipper phone number is constant, and handling it on the server (to make the lab user life easier) see docs here https://vsoch.github.io/freegenes/docs/development/setup#freegenes-node-contact. What would be the reason to expose it (forcing entry?) for the lab staff?

And the same for PTA - we define it as a settings config value here https://vsoch.github.io/freegenes/docs/development/setup#shipping-secrets and then the lab user doesn't need to think about it. Are there cases when you don't want it entered? Why should we make it a variable?

For your specific concern, other adopters of a BioNode will set the variables on the server just as we've done here. It's a one time, non-changing variable so it's very appropriate for entry in this fashion, as opposed to something like shipping dry ice weight which will change regularly. The basic requirements for deployment *are* having the technical chops to do it, and I've put together the guide that I linked so they can fill out that one config.py file once, and then never have to think about it again.

**Comment by vsoch** [comment]
okay the orders table will have two dates, updated and created

![image](https://user-images.githubusercontent.com/814322/65353646-a54a7b80-dbbb-11e9-96f9-4f9b67ba53a6.png)

okay give it a look! For the sorting, you should be able to click the column header for any field to sort ascending or descending.

**Comment by hverdonk** [comment]
I just discussed with Marc, and he agrees with you that for now, we should leave the phone number and PTA number as static, unchanging variables in the config file. Please disregard my third point :).

The sort is great, thank you! It makes it so much easier to get to the most recent requests.

**Comment by vsoch** [comment]
Great! Let me know if anything else needs tweaking. Closing issue, as I think we covered all points!
