### ISSUE TITLE
PlateMap from API

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#58]
hey @Koeng101 ! As requested, here is the output of getting a plate-map based on an order-id and a shipping barcode. The actual API returns a path to a file on AWS, and then I parse in raw text (and it's csv) so I can read in with Python's csv to get two rows - the first is header, the second is the content:

```python
[['Name',
  'Insertion point name',
  'Vector name',
  'Insert length',
  'Construct length',
  'Insert sequence',
  'Construct sequence',
  'Well Location',
  'Yield',
  'NGS',
  'Yield (ng)',
  'Product type',
  'Plate ID'],
 ['BBF10K_000014',
  'BbsI_BbsI',
  'pOpen_v3.0',
  '436',
  '2437',
  'GGTCTCAAATGATTAAAAAGTATGAGGTGATGTATATTTTGGATCAAGACGTCAAGGACACTAAGGAGTTAGTGACAAAGCTGGATGCAATCTTGGCTGAAAACGGAAAGATTCTGGAGTCGAACGACTTAGGTTTACTGGATTTTACATACGAAATCAATCACAAGAAAAAGGGCTTTTATCACGTGGTGATTGTCGAAGCGACGACACAGGCAATCAAGGAATTTGAACGTATCGCTAAGATCGACAAAAATGTTGTACGCACCCTGGTCCTTAACACTGAAAATATTCAAAACTACGAACAATCCGTCGTACTGTCTAAGACCGACATGACAAAGTATGAGGAGGAGCAGCGCGAAAAGAAAAATTTTCGCAAACCTTTCATCAAGCGTGAAGAAGCGGCTGTAAAGGAAAGCAAGTGAAGAGCTTAGAGACC',
  'GGTCTCAAATGATTAAAAAGTATGAGGTGATGTATATTTTGGATCAAGACGTCAAGGACACTAAGGAGTTAGTGACAAAGCTGGATGCAATCTTGGCTGAAAACGGAAAGATTCTGGAGTCGAACGACTTAGGTTTACTGGATTTTACATACGAAATCAATCACAAGAAAAAGGGCTTTTATCACGTGGTGATTGTCGAAGCGACGACACAGGCAATCAAGGAATTTGAACGTATCGCTAAGATCGACAAAAATGTTGTACGCACCCTGGTCCTTAACACTGAAAATATTCAAAACTACGAACAATCCGTCGTACTGTCTAAGACCGACATGACAAAGTATGAGGAGGAGCAGCGCGAAAAGAAAAATTTTCGCAAACCTTTCATCAAGCGTGAAGAAGCGGCTGTAAAGGAAAGCAAGTGAAGAGCTTAGAGACCCGCTGAGGTGTCAATCGTCGGAGCCGCTGAGCAATAACTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCATGGTCATAGCTGTTTCCTGAGAGCTTGGCAGGTGATGACACACATTAACAAATTTCGTGAGGAGTCTCCAGAAGAATGCCATTAATTTCCATAGGCTCCGCCCCCCTGACGAGCATCACAAAAATCGACGCTCAAGTCAGAGGTGGCGAAACCCGACAGGACTATAAAGATACCAGGCGTTTCCCCCTGGAAGCTCCCTCGTGCGCTCTCCTGTTCCGACCCTGCCGCTTACCGGATACCTGTCCGCCTTTCTCCCTTCGGGAAGCGTGGCGCTTTCTCATAGCTCACGCTGTAGGTATCTCAGTTCGGTGTAGGTCGTTCGCTCCAAGCTGGGCTGTGTGCACGAACCCCCCGTTCAGCCCGACCGCTGCGCCTTATCCGGTAACTATCGTCTTGAGTCCAACCCGGTAAGACACGACTTATCGCCACTGGCAGCAGCCACTGGTAACAGGATTAGCAGAGCGAGGTATGTAGGCGGTGCTACAGAGTTCTTGAAGTGGTGGCCTAACTACGGCTACACTAGAAGAACAGTATTTGGTATCTGCGCTCTGCTGAAGCCAGTTACCTTCGGAAAAAGAGTTGGTAGCTCTTGATCCGGCAAACAAACCACCGCTGGTAGCGGTGGTTTTTTTGTTTGCAAGCAGCAGATTACGCGCAGAAAAAAAGGATCTCAAGAAGGCCTACTATTAGCAACAACGATCCTTTGATCTTTTCTACGGGGTCTGACGCTCAGTGGAACGAAAACTCACGTTAAGGGATTTTGGTCATGAGATTATCAAAAAGGATCTTCACCTAGATCCTTTTAAATTAAAAATGAAGTTTTAAATCAATCTAAAGTATATATGAGTAAACTTGGTCTGACAGTTACCAATGCTTAATCAGTGAGGCACCTATCTCAGCGATCTGTCTATTTCGTTCATCCATAGTTGCCTGACTCCCCGTCGTGTAGATAACTACGATACGGGAGGGCTTACCATCTGGCCCCAGTGCTGCAATGATACCGCGAGAACCACGCTCACCGGCTCCAGATTTATCAGCAATAAACCAGCCAGCCGGAAGGGCCGAGCGCAGAAGTGGTCCTGCAACTTTATCCGCCTCCATCCAGTCTATTAATTGTTGCCGGGAAGCTAGAGTAAGTAGTTCGCCAGTTAATAGTTTGCGCAACGTTGTTGCCATTGCTACAGGCATCGTGGTGTCACGCTCGTCGTTTGGTATGGCTTCATTCAGCTCCGGTTCCCAACGATCAAGGCGAGTTACATGATCCCCCATGTTGTGCAAAAAAGCGGTTAGCTCCTTCGGTCCTCCGATCGTTGTCAGAAGTAAGTTGGCCGCAGTGTTATCACTCATGGTTATGGCAGCACTGCATAATTCTCTTACTGTCATGCCATCCGTAAGATGCTTTTCTGTGACTGGTGAGTACTCAACCAAGTCATTCTGAGAATAGTGTATGCGGCGACCGAGTTGCTCTTGCCCGGCGTCAATACGGGATAATACCGCGCCACATAGCAGAACTTTAAAAGTGCTCATCATTGGAAAACGTTCTTCGGGGCGAAAACTCTCAAGGATCTTACCGCTGTTGAGATCCAGTTCGATGTAACCCACTCGTGCACCCAACTGATCTTCAGCATCTTTTACTTTCACCAGCGTTTCTGGGTGAGCAAAAACAGGAAGGCAAAATGCCGCAAAAAAGGGAATAAGGGCGACACGGAAATGTTGAATACTCATACTCTTCCTTTTTCAATATTATTGAAGCATTTATCAGGGTTATTGTCTCATGAGCGGATACATATTTGAATGTATTTAGAAAAATAAACAAATAGGGGTTCCGCGCACCTGCACCAGTCAGTAAAACGACGGCCAGTAGTCAAAAGCCTCCGACCGGAGGCTTTTGACTTGGTTCAGGTGGAGTGGGAG',
  'A01',
  'N/A',
  'Pass',
  'N/A',
  'Glycerol stock',
  'pSHPs0627B165998SH']]
```

**Comment by vsoch** [comment]
I'm going to try creating a function that will be something like:

```python
> rows = client.order_platemaps(sfdc_id)
```
To combine all plate map sheets from containers across an order, so it's one function to parse an entire order. Right now (using their provided API functions) the function would need to do one container barcode at a time:

```python
>  rows = client.order_platemaps_by_barcode(sfdc_id=sfdc_id, barcode=barcode) 
```
which seems like too much work, or at least something we can implement for the user.

**Comment by vsoch** [comment]
okay so looks like we need to map these header fields:

```
['Name',
 'Insertion point name',
 'Vector name',
 'Insert length',
 'Construct length',
 'Insert sequence',
 'Construct sequence',
 'Well Location',
 'Yield',
 'NGS',
 'Yield (ng)',
 'Product type',
 'Plate ID']
```
to the Part fields:

```
 dict_keys(['_state', 'uuid', 'time_created', 'time_updated', 'status', 'name', 'description', 'gene_id', 'part_type', 'original_sequence', 'optimized_sequence', 'synthesized_sequence', 'full_sequence', 'genbank', 'vector', 'primer_forward', 'primer_reverse', 'barcode', 'translation', 'ip_check_date', 'ip_check', 'ip_check_ref', 'author_id'])
```

 - Name maps nicely - name from the plate map is the gene_id.
 - We leave description empty? Maybe use "Vector Name?" Insertion point name?
 - I'm not sure what to do with Construct length and Insert length
 - Construct sequence maps to original_sequence (or another sequence?)
 - I don't know how to derive the part_type
 - For uuid, time_created, and time_updated, these are generated automatically
 - For status, the default is "None" but I'm guessing we might want to do "Complete" ? How would the status be anything but complete if we are importing something that is shipped to the lab?
 -  For the author - is the author the person importing the plates?

I'm not sure about the rest of the fields - there seem to be some from the platemap that should belong when we create plates, but we'd need to create Parts and Samples first.

**Comment by vsoch** [comment]
And I'm seeing a lot of the database entries don't have barcode. I want to double check that the barcode from the shipment shouldn't map to here (I would guess it should be a lab barcode).

**Comment by vsoch** [comment]
And to give you full details of what I'm working on - we will expose a button at the top of an order items page to "Import" iff the order has a "shipments" field, meaning we can look them up with barcodes and derive a master plate map. The server will actually run this as a background task, because the queries to (at least the staging) api aren't as fast as one would like. The function that the task runs will look like the following:

Notice that we take a uuid (a sfdc_id that identifies an order in Twist) and a user id, which I'm doing now to attribute some author to the order (this might not be correct, but it's reasonable to start with if an author is required).

```python
def import_order_task(uuid, user_id):
    '''Based on an order id (uuid is the order sfdc_id in Twist)
       use FreeGenes Python to derive a list of plates (the PlateMap)
       and import plates into FreeGenes that don't exist.
    '''
    # These are imported within the task so the task can run as an isolated unit
    from fg.apps.main.models import Part
    from fg.apps.users.models import User
    from fg.apps.factory.twist import get_client

    print('RUNNING IMPORT ORDER TASK WITH UUID %s' % uuid)

    client = get_client()

    # This function returns a compiled sheet of platemaps
    rows = client.order_platemaps(sfdc_id=uuid)
    print("Found %s total entries" % (len(rows) -1))
  
    # Separate header list 
    headers = rows.pop(0)

    # The user importing is the author?
    user = User.objects.get(id=user_id)

    # Get List of Parts that aren't in FreeGenes
    names = [row[headers.index("Name")] for row in rows]
    existing = Part.objects.filter(gene_id__in=names).values_list('gene_id', flat=True)

    # TODO: need to understand how to do this mapping.
    for row in rows:
        name = row[headers.index("Name")]
        if name not in existing:
            part = Part.objects.create(name=name,
                                       status="Complete",
                                       author=user,
                                       original_sequence=row[headers.index('Construct sequence')],
             ..... # not yet written
```

At the end of the above, we need to complete the mapping to a Part, and then I suspect create Samples / Plates associated with it. That's as far as I am thinking about this!

**Comment by Koeng101** [comment]
None of the parts should be new - and they also shouldn't have `primer_for, primer_rev, barcode`. These are genetic elements that are built into the sequence that we sent them. I think we should just not allow importation at all if the parts aren't all in the database already. If this becomes a problem later, we can handle it then. Right now, there is too much data in the "part" table to be able to derive a part object from the platemap that Twist sends us.

**Comment by vsoch** [comment]
okay - so just to confirm a few things:

 1. Ok - so we aren't importing Parts - what exactly are we importing from the PlateMaps then? Could you clarify the Model we are importing to, and how the fields are mapped? What buttons / views can I make you?
 2. You want to completely remove barcode, primer_forward, and primer_reverse from the "Part" model.

**Comment by Koeng101** [comment]
1. What we're mainly looking at doing is import of physicals, primarily wells and plates (which necessitates samples, since the only way to link wells and plates to parts is with samples). Writing another comment with that information

2. Totally my bad for that, pronouns are bad, by "they" I meant the new lines from the CSV file we got from Twist. Each line references a part, but doesn't reference barcode, primer_for, or primer_rev, which is why I don't really want the ability to import them directly right now.

**Comment by vsoch** [comment]
okay - could you please give the mapping from the PlateMap table to creating the physicals? For example, right now a Well doesn't require a sample, so I could create a well for each row in the table. The most information (I think?) I have is the well location, for example, A01: and that would map to address:

```python
    address = models.CharField(max_length=32, blank=False)
```
but volume, quantity, and media I assume would be empty?

```python
    volume = models.FloatField()
    quantity = models.PositiveIntegerField(default=0, null=True, blank=True)
    media = models.CharField(max_length=250)
```
so after creating the set of wells, I need to create the Plate object to add them to. The obvious field is "Plate ID" which is relevant for Twist, but I don't see other identifiers like it in our system. Specially, I'd need to know:

```
    plate_type = models.CharField(max_length=32, choices=PLATE_TYPE, blank=False)
    plate_form = models.CharField(max_length=32, choices=PLATE_FORM, blank=False)
    status = models.CharField(max_length=32, choices=PLATE_STATUS, blank=False)
    name = models.CharField(max_length=250, blank=False)
    plate_vendor_id = models.CharField(max_length=250, blank=True, null=True)

    # This is a proposed addition so we generate wells from plates with known dimensions
    height = models.IntegerField(blank=False, default=DEFAULT_PLATE_HEIGHT)
    length = models.IntegerField(blank=False, default=DEFAULT_PLATE_LENGTH)

    container = models.ForeignKey('Container', on_delete=models.CASCADE)
```
(I removed protocol and notes). I need this basic information to write this import of physicals, and it seems like there isn't enough metadata with just a plate map. Let me know how you usually do this!

**Comment by Koeng101** [comment]
You're right, we do assume some things!

# Plates
Each plate map file is a single `Plate` object.

If in that plate map, "Product type" is "Clonal Genes", then the plate object would be:
```
USER_INPUT -> plate.name
USER_INPUT -> plate.container
Plate ID -> plate.plate_vendor_id
"plasmid_plate" -> plate.plate_type
"standard96" -> plate.plate_form
"Stocked" -> plate.status
8 -> plate.height
12 -> plate.length
0 -> plate.thaw_count
```
If in that plate map, "Product type" is "Glycerol stock", then the plate object would be:
```
USER_INPUT -> plate.name
USER_INPUT -> plate.container
Plate ID -> plate.plate_vendor_id
"glycerol_stock" -> plate.plate_type
"standard96" -> plate.plate_form
"Stocked" -> plate.status
8 -> plate.height
12 -> plate.length
0 -> plate.thaw_count
```

# Wells
Each line of the plate map file would be a `Well` object.

With the headers being: ```['Name',
 'Insertion point name',
 'Vector name',
 'Insert length',
 'Construct length',
 'Insert sequence',
 'Construct sequence',
 'Well Location',
 'Yield',
 'NGS',
 'Yield (ng)',
 'Product type',
 'Plate ID']```

The ones that really matter are "Name", "Well Location", "Yield", and "Product type" (and "Construct sequence")

If in that plate map, "Product type" is "Glycerol stock", then the well object would be:
```
plate above ^ -> well.plate_uuid
Well Location -> well.address (removing extraneous 0s will be required here)
50 -> well.volume (this is how much liquid they ship)
"glycerol_lb" -> well.media
```
If in that plate map, "Product type" is "Clonal Genes", then the well object would be:
```
plate above ^ -> well.plate_uuid
Well Location -> well.address (removing extraneous 0s will be required here)
0 -> well.volume (they send us dried DNA)
Yield (ng) -> well.quantity # https://nebiocalculator.neb.com/#!/dsdnaamt in fmol
```
Formula for quantity is ` moles dsDNA (mol) = mass of dsDNA (g)/((length of dsDNA (bp) x 617.96 g/mol) + 36.04 g/mol)`, where the "length of dsDNA" is the length of "Construct sequence" and the Yield ng is the "mass of dsDNA".

For example, a 3000bp piece of DNA with 2000ng would 1079fmol, so well.quantity = 1079

**Comment by Koeng101** [comment]
(For plate height and length it's because of 96 well plate format, which is what they ship in)

**Comment by vsoch** [comment]
Oh I see - so having a PlateMap with 500 rows means one plate, and that many wells? Or still an unknown number of plates, each with 96 wells? A few questions!

 - where do the dimensions 8, 12, and 0 come from? In the current database we have 16 and 24. Just seeing your post - how do we know that 96 wells means 8 by 12?
 - What do you mean by user input? For example, an import for the last (fulll order) was over 500 rows. Are you saying that the user needs to provide a name and container for every single entry (not recommended!) or we can ask for some prefix or a shared name?
 - The container makes sense, we can provide the user a form after they click the button to select it (and input other metadata).

So I think the biggest challenge for now is dimension, and if there is more than one plate for a set of rows, that might be a challenge too. Actually, is each plate associated with one barcode sent? If that's the case, then we can split apart the processing based on the barcode (and make a new Plate per barcode). For dimension, if there is a set mapping of dimensions to height and length (e.g., 96 --> 8xx12) then let's write that out, the function will use it as a lookup, and return an error message if a new dimension is encountered.

**Comment by Koeng101** [comment]
I think PlateMaps actually max out at 96 rows, for Twist's system through their website

1. 8 and 12 are the number of wells in the actual plate (ie, we know because they sit on our desk). Since you probably don't have them laying around, here is a pic online to show what they look like. http://icebergcoworking.com/wp-content/uploads/2017/11/96-Well-Plate-Template.jpg I'm actually curious where our database got 16 and 24 from. I think that might be from using the old API code that generated potential wells from 16 and 24 so we can have 384 well plates in our system. We don't really use 384 well plates right now, though. Height and Length could also be derived from the plate type, since standard96 will always be 8x12, and standard384 will always be 16x24

2. Oh - they must be importing several different plates at once. The Plate ID will be the same for several rows (up to 96). That encompasses a single `Plate` object, which would need user input for where they physically put the plate and for what they labeled it. In the 500 row case, they'd probably need to provide a name for 6 plates or so.

3. You could replace "barcode" with Plate ID and the above makes sense. With the picture above, you can also probably see what "well address" means now. 

The barcode included in "part" is actually part of an interesting DNA-level trick to make validation of samples easier. By cleaving the DNA in the middle using a very rarely occurring restriction enzyme, I-SceI, you can cut our circular plasmid DNA into a long string. That long string you can read through a Nanopore sequencer (https://www.youtube.com/watch?v=RcP85JHLmnI) to identify a certain DNA. If you use a computer with enough GPU power while running the Nanopore, you can actually identify individual parts by their barcodes as they run through the machine. Since you can change polarity of the pores on the Nanopore device, you can then suck in about 20 base pairs, and then spit out those 20 base pairs, repeating the process rapidly to quantify the relative quantities of DNA within a pool of DNA. You can also target the sequencing of certain part fragments with the Nanopore device by identifying the DNA barcodes and only dragging the full sequence in of the parts you want. 

In any case, the "barcodes" in parts are just DNA samples, and have no actual normal "barcoding" abilities.

**Comment by vsoch** [comment]
Ah this is totally starting to make sense! Since we'll need to parse over the plate data before presenting to the lab staff (so we can ask for N names) what I'll do is create an import tab on the details page, that way we only query that Twist API endpoint once.

And I'm guessing that we can determine if a plate has already been imported based on the plate_vendor_id?

**Comment by Koeng101** [comment]
Exactly! On that note, we should probably have `unique=True` as an option on `plate_vendor_id`

**Comment by vsoch** [comment]
Just for a heads up - it doesn't look like "plasmid_plate" is an option in our current plate types:

```python
    PLATE_TYPE = [
        ('archive_glycerol_stock','archive_glycerol_stock'),
        ('glycerol_stock','glycerol_stock'),
        ('culture','culture'),
        ('distro','distro'),
    ]
```
so I'm adding it

```python
    PLATE_TYPE = [
        ('archive_glycerol_stock','archive_glycerol_stock'),
        ('plasmid_plate','plasmid_plate'),
        ('glycerol_stock','glycerol_stock'),
        ('culture','culture'),
        ('distro','distro'),
    ]
```

**Comment by vsoch** [comment]
It looks like "Plasmid" is an option for a Sample, or for a Part.

**Comment by vsoch** [comment]
Would it be okay to ask the importer (lab staff) to specify the height and length for each plate? I am hugely uncomfortable with making the assumption - it will just increase fields in the form a little bit :)

**Comment by vsoch** [comment]
I think I'll throw in PlateForm too - there are too many choices, and I anticipate that the user would eventually want to know what this is being set to!

**Comment by vsoch** [comment]
@Koeng101 when you say remove trailing zeros - I don't see any - there is only a trailing zero for "ten" and then a zero for ones units, e.g.,

```
 'B01',
 'B10',
 'B11',
 'B12',
 'B02',
```
Did I get the wrong field? I'm looking at "Well location" for the address. If there is some possibility of a trailing 0, I can add a strip("0") if you think absolutely necessary.

**Comment by vsoch** [comment]
And just to confirm - I can take the quantity verbatim (I don't need to calculate it as you showed me how)

**Comment by vsoch** [comment]
@Koeng101 - this is now implemented (and if you want to take a look over) https://github.com/vsoch/freegenes/blob/master/fg/apps/factory/views/twist.py#L133 and it's run as a task. When you test this out please let me know so that I can monitor the server! Specifically, we need to be cautious because:
 - it's almost impossible to develop locally since my ip address would need to be whitelisted on a daily basis, so I developed it half on our server, half locally, and have tested in pieces but not in full
 - the Twist API is providing older data, so I'm not sure how would be best to test an import

We might want to wait to get the server updated with production, and then do import for an actual order. Either way - please give me a heads up when you want to do this so I can literally watch and catch any issues immediately! I'm going to close here for now since we finished, and I'll respond to issues as they come up.
