### ISSUE TITLE
Question: Any reason to use uuid4?

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#6]
If we use Django default (increasing integers) we generate more user friendly URLs.

**Comment by Koeng101** [comment]
For parts and collections, I'd like to be able to use UUIDs as universally usable (not dependent upon however many other parts or collections are in your database). My bionet node might share a collection with another node, but we should both be able to know that our 2 collections are supposed to be the same.

For consistency purposes it might be hard to switch as well, we have a few barcodes on plates that have been physically shipped to people.

**Comment by vsoch** [comment]
okay - that's good enough reason for me. When we import data (or if a second node replicates data) we'd want to specify the uid, which is easy to do with uuid4 (unlikely to work with integer).
