### ISSUE TITLE
Download csv of distribution

### ISSUE THREAD

**Issue by Russell-Tran** [vsoch/freegenes#66]
The problem is that when you download a csv of the distribution, it shows 3000 genes when it should show ~ 40. Thanks :)

**Comment by vsoch** [comment]
Could you please link to the page with the download link? Thanks!

**Comment by vsoch** [comment]
Hey @Russell-Tran I'm testing this out, and I think what you are seeing is correct. You aren't seeing genes, you are seeling wells. For example, for the [open enzype 1 distribution](https://freegenes.dev/e/distribution/287d661f-05e3-4272-b545-cb1a4f2fc7f7) we have a total of 1 platesets.

```python
dist.platesets.all()                                                                                                                                                
Out[5]: <QuerySet [<PlateSet:OpenEnzyme,72>]>
```
The plateset has 72 plates, as you can see. For each plate, we can sum up the wells:

```python
plateset = dist.platesets.all()[0]
wells = 0                                                                                                                                                           

for plate in plateset.plates.all(): 
    wells += plate.wells.count() 
```

and we get the exact number of rows in that sheet.
```python
wells
# 3024
```
This is how I believe @Koeng101 requested the implemented, let me know if something isn't clear or some different endpoint is desired.

**Comment by vsoch** [comment]
If there is some additional export that you think should be provided in the interface, and you are not able to use the [freegenes API client](https://vsoch.github.io/freegenes-python/docs/getting-started/python-client) to get it, I'd be happy to have some discussion here about what you are looking for, confirm with @Koeng101, and add (likely) tomorrow.

**Comment by Russell-Tran** [comment]
Oh thanks for clearing that up! I was hanging out with Keoni at SBB and we were messing around on the website and he told me to put that lol

________________________________

**Comment by vsoch** [comment]
You can see the original discussion here -> https://github.com/vsoch/freegenes/issues/16 the request was for plates and wells, so possibly he was thinking of adding another export, or just forgot. :P

**Comment by vsoch** [comment]
Closing issue here - if there is some new endpoint desired, Keoni will let me know!
