### ISSUE TITLE
Create, update, delete API for all objects

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#69]
**Is your feature request related to a problem? Please describe.**
Would like option to manually import DNA samples to API.

**Describe the solution you'd like**
I would like there to be a RESTFUL API in which I can create, update, and delete any object in our database.

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
@Koeng101 could you please provide all required fields for create, for each of the classes you would like added? Thanks!

**Comment by vsoch** [comment]
I can't find an easy way to provide the different detail / list views for a viewset (and it's eating up hours of time) so each is going to provide a single serializer with all fields, and the user will need to paginate.

**Comment by vsoch** [comment]
hey @Koeng101!  I am really wanting to support you and Hannah, so I was able to put in 6 hours of focused work today to add all create, update, delete endpoints across models -> 
 https://github.com/vsoch/freegenes/pull/72

You can see the basic parameters (and what is required) in the [docs page](https://freegenes.dev/api/docs/), and I've also created wrappers for each endpoint with FreeGenes Python, which should (in the long run) provide an easier interface to accomplish the same. https://vsoch.github.io/freegenes-python/docs/getting-started/python-client#post-create-endpoints

I'm starting to see little stars in my vision so I probably need to step away from a computer screen, I wasn't able to start the refactoring of Twist to import from the csv, but will be able to work on this during the week. I hope this helps a bit!
