### ISSUE TITLE
Text Field Updates

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#70]
We're currently in the process of updating some of the placeholder text on the website; however, some of it seems inaccessible. If you could show me how to change it myself, I'd appreciate it :). If that's not possible, could you please update the following on the Catalog page:

Collection - A group of parts.

Parts - Genetic elements are gene sequences that do things. A part is the information about a genetic element that we offer or would like to offer in the future. 

Distribution - A group of related parts, corresponding to a plate of genetic elements that you can order. The parts may represent an entire collection, or a subset of one.

In addition, we'd like to change the name "Outgoing Orders" to "Shipments." Thank you!

**Comment by vsoch** [comment]
hey @hverdonk ! For future reference, all the text is in the GitHub repo here - if you do a search you'll find it in the templates. You can also use grep in the repository root to find it. For example:

```bash
$ grep -R "text I want to find"
```
In this case, all text is in  gedit fg/apps/main/templates/catalogs/catalog.html.

I've just fixed these for you, and the commit closed the issue (click on it to see changes!)
