### ISSUE TITLE
Sample has no required fields

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#71]
The current sample model has no required fields, meaning that a user with create permission (without providing any parameters) could create an empty object:

![image](https://user-images.githubusercontent.com/814322/66271866-d91ad780-e830-11e9-971b-3dfb8581721b.png)

I can check for absence of parameters using the Python Client, but can't control raw (Restful requests) to the API. Samples should have some minimum set of required fields.

**Comment by vsoch** [comment]
I made part and wells required - this seems reasonable because you can't create a sample without having an associated part, and putting it somewhere!

![image](https://user-images.githubusercontent.com/814322/66273558-ee98fd00-e842-11e9-97e8-25ea89dc54b1.png)

**Comment by Koeng101** [comment]
Could we get a
