### ISSUE TITLE
Importing plates from Factory

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#74]
# Factory Imports
- [x] Create Order page
- [x] Link Plates to Orders
- [x] Checkbox for adding samples into Plate

## Create Order page
For any given synthesis company, we want to see information about orders that we currently have out with them. This will require a few different fields:

- status ( String, Enum=['Planned','In-Production','Complete','Abandoned'] )
- start date ( DateTime [user defined] ) 
- finish date ( DateTime [user defined] )
- estimated price ( Float )
- real price ( Float )
- invoices ( List of Invoice objects )

Invoices, the last object, are just PDF files that have the status "Unpaid" and "Paid" along with a section for "notes" about that invoice. Invoices are simply to track expenditures so I can sync up with our financial director.

Both the start date and finish date should allow user defined data (like a calendar pop up), so that is very easy to import older data.

I imagine a simple form interface where you can manually input each one of those data points.

## Link Plates to Orders
When importing a plate, there should be the option to import it as associated with a DNA Order. Later, we can track which plates came from which particular orders.

## Checkbox for adding samples into Plate
When you import a plate into the system, you have the option to add a sample in as well. If a plate is associated with an order, first we would check for if a sample is already used for that particular part. If it is, we simply use that sample. If not, we must generate a sample object.

When you click the checkbox, you also have the option to put in the Vendor, which is the Sample.vendor for all samples generated.

### Sample import
For each row in a plate map, we specifically care about the "Name", which maps to the Part.gene_id
```
row['Name'] == Part.gene_id -> sample.part_uuid
"Confirmed" -> Sample.status
"Vendor_Confirmed" -> Sample.evidence # Replaces "Twist_Confirmed"
Vendor -> Sample.vendor
```
Each sample is put into the well that is also generated by the line of the plate map.

**Comment by Koeng101** [comment]
I will check this tomorrow morning, just comment here if you need anything else!

**Comment by vsoch** [comment]
Design wise, I think that it would be easier to link one or more Plates to a FactoryOrder, that way the Plate doesn't have (at least a direct) foreign key to one order. The reason is because we don't want to have imports from the orders file to the main file, and from the main file to the orders file (this will trigger a circular import error).

**Comment by vsoch** [comment]
Hmm I also think we need a basic representation of a vendor (e.g., Twist) to have as a field (ForeignKey) for a FactoryOrder.

**Comment by vsoch** [comment]
okay preview of additions to models and admin interface - 

![image](https://user-images.githubusercontent.com/814322/66406273-5ec98f00-e9b9-11e9-8647-978751b18ed2.png)

Adding a FactoryOrder has the nice little date pickers and what not.

![image](https://user-images.githubusercontent.com/814322/66406354-7e60b780-e9b9-11e9-92c9-03eeeaf3c1fa.png)

Working on adding a field to specify an Order on the Plate Map upload form, and link to this page if the Order needs to be created.

**Comment by vsoch** [comment]
If a plate has a plate_vendor_id, and we are already associating the entire plate with a Vendor, it doesn't make sense anymore to have a sample associated with a vendor too. That hugely complicates the database logic because Vendor is a Factory model, and Sample should be agnostic to that (but we can easily find samples for some vendor given associated plates).

**Comment by vsoch** [comment]
Since it's represented as a char field, we could put the unique id there, and then minimally that would have a link queryable based on the string. I'll do that for the time being since the original vendor model has a string.

**Comment by Koeng101** [comment]
> why does the FactoryOrder not have any name? Names have been useful for Hannah to refer to (outgoing orders) so I am thinking they might be useful here as well.

Yea you're right should have a name!

> Just for my own understanding - the plate map examples you've sent me I assumed were for one order, and were named based on the plate_vendor_id. I can confirm this by looking at the unique values we have in the database:

I might have sent you plate maps from one order only, but usually there are multiple plate maps per order that you need to import.

> But it isn't the case that the plate_map_id corresponds with the order number, correct? If it were the case that plate_vendor_id, or one plate map import, corresponded with the order number, then we would have that already represented. 

If vendor was stored in the order object, then having vendor be "Twist" on the Plates object would be redundant. (I think this answers that)

> Design wise, I think that it would be easier to link one or more Plates to a FactoryOrder, that way the Plate doesn't have (at least a direct) foreign key to one order. The reason is because we don't want to have imports from the orders file to the main file, and from the main file to the orders file (this will trigger a circular import error).

What is the difference between FactoryOrder and an order? I'm not really sure what this is saying.

> Hmm I also think we need a basic representation of a vendor (e.g., Twist) to have as a field (ForeignKey) for a FactoryOrder.

That makes sense to me!

> If a plate has a plate_vendor_id, and we are already associating the entire plate with a Vendor, it doesn't make sense anymore to have a sample associated with a vendor too. That hugely complicates the database logic because Vendor is a Factory model, and Sample should be agnostic to that (but we can easily find samples for some vendor given associated plates).

Yea, that's approximately what I was thinking of. If a Plate object is associated with an Order object, we should be able to find all the Plate objects that are linked through that Order object, to discover if there are redundant samples, in which case we don't generate a new sample.

**Comment by vsoch** [comment]
Also, there is a bit of a disconnect when you talk about relationships between plates and parts:

> When you import a plate into the system, you have the option to add a sample in as well. If a plate is associated with an order, first we would check for if a sample is already used for that particular part. If it is, we simply use that sample. If not, we must generate a sample object.

Plates are not related to parts directly, plates have wells which are related to samples because a Sample has both part, composite part, and then a list of wells that are relevant. So we would need to first check if a sample exists for the part, regardless of the plate, and then if not, add the well. If the sample associated with the part already exists, do we still add the well from the new plate? I'm not totally sure how that makes sense.

**Comment by vsoch** [comment]
> If vendor was stored in the order object, then having vendor be "Twist" on the Plates object would be redundant. (I think this answers that)

okay, although this was there for your original design, and it's there now - just want to make that clear! It's redundant, yes.

> What is the difference between FactoryOrder and an order? I'm not really sure what this is saying.
 
An order is when someone comes to the site and checks out a cart - it's a FreeGenes "outgoing" order if you will. A FactoryOrder is an incoming order for gene stuffs, and only available to admins, etc.

I'm still a bit confused about samples - doesn't a plate with wells come with "goop" inside of it (samples) that need to be added to the database? What's the point of adding a new plate and wells if we don't represent the content?

**Comment by vsoch** [comment]
Also the current logic (per a previous discussion) was only to import wells for already existing parts (I noted this in the code)

```
    # We will only import wells for existing parts
    existing = Part.objects.filter(gene_id__in=names).values_list('gene_id', flat=True)
```
So - what exactly is a vendor sending, if it's not new parts that need samples created?

**Comment by Koeng101** [comment]
> So - what exactly is a vendor sending, if it's not new parts that need samples created?

Responding to rest, but quickly, the vendor is sending 2 copies of a sample in 2 different forms. That sample can sometimes exist already as a sample but just didn't succeed in cloning, which is why we can't just check for if a sample exists already.

**Comment by vsoch** [comment]
Okay so here is the logic I'm hearing:

 1. we check for all existing parts that we have based on their name, the "Name" field in the csv which links up to a gene_id for a Part
 2. If the part doesn't already exist - do nothing. We aren't adding new parts.
 3. If the part does exist, get or create it's associated plate, and get or create each well represented in the csv.
 4. For each well, get the associated part based on looking up the gene_id again.
 5. For the part, we then have a sample_set. The random one I'm grabbing has two samples. 

So - should the above not have two samples, if it's linked to one part? How do we determine if a new sample should be generated, or one of the ones included?

Given that we know the answer to the above (call this point 6.)

 7. If no sample exists, create one and point it to the part. Add the well to the sample too that we are importing.
 8 . If some sample (which one?) exists and is "the right one" (how do we know?) then we don't need to create a sample or re-add to the part (it's already there) but we need to add the well to the sample.

  

I think what I'm hearing is that a sample, which is associated with wells (a group of many) and a part, given that the same part is import in a new plate, and given that the sample already exists for the part, we can add the new well to its list of wells, and the part stays the same.

**Comment by Koeng101** [comment]
> Plates are not related to parts directly, plates have wells which are related to samples because a Sample has both part, composite part, and then a list of wells that are relevant. So we would need to first check if a sample exists for the part, regardless of the plate, and then if not, add the well. If the sample associated with the part already exists, do we still add the well from the new plate? I'm not totally sure how that makes sense.

We need to check if a Sample exists already associated with a certain FactoryOrder. To figure out if a sample already exists given a part, you have to transverse through FactoryOrder -> Plate -> Wells -> Samples -> Part. Many parts already have samples for parts we ordered, we just don't trust their sequencing enough to distribute them to people.

> An order is when someone comes to the site and checks out a cart - it's a FreeGenes "outgoing" order if you will. A FactoryOrder is an incoming order for gene stuffs, and only available to admins, etc.

Ok, I'll use that `FactoryOrder` now when I refer to factoryorders

> Also the current logic (per a previous discussion) was only to import wells for already existing parts (I noted this in the code)

I'm of the preference that we do not allow any importation of any plate map that doesn't have all parts within it represented in our database. Rather than only importing wells with existing parts, check for if all parts are in the csv file first, and if each line doesn't have a matching part, throw an error to the user.

> So - what exactly is a vendor sending, if it's not new parts that need samples created?

The vendor is specifically sending us Samples of Parts that we already have.

**Comment by vsoch** [comment]
> We need to check if a Sample exists already associated with a certain FactoryOrder. To figure out if a sample already exists given a part, you have to transverse through FactoryOrder -> Plate -> Wells -> Samples -> Part. Many parts already have samples for parts we ordered, we just don't trust their sequencing enough to distribute them to people.

so you are saying that the Sample.vendor (which will be the FactoryOrder id) is what determines if a sample exists or not - but won't every FactoryOrder have a new id by default? Are you saying that the Sample.vendor can't be the unique id of the particular order, but perhaps the name? So for the above, point 8 would be:

 8. If samples exist, check for one with vendor == "Twist" (or the FactoryOrder name) If this sample associated with the vendor exists (even if from a different order) then we don't need to create a sample or re-add to the part (it's already there) but we need to add the well to the sample.

**Comment by vsoch** [comment]
And just to add some clarity - when you say

> FactoryOrder -> Plate -> Wells -> Samples -> Part

That's a bit of circular logic, because we're running the create function that generates the relationship between those things to begin with. We can't do that lookup if we haven't created it yet (but we can do the logic that I'm walking through).

**Comment by vsoch** [comment]
> I'm of the preference that we do not allow any importation of any plate map that doesn't have all parts within it represented in our database. Rather than only importing wells with existing parts, check for if all parts are in the csv file first, and if each line doesn't have a matching part, throw an error to the user.

Ah ok this is important! I'm currently allowing for partial imports but I can do this check at the getgo.

**Comment by Koeng101** [comment]
> So - should the above not have two samples, if it's linked to one part? How do we determine if a new sample should be generated, or one of the ones included?

This is a very biologically relevant question! Basically, Samples aren't meant to represent "samples" (like liquid in a well). If it did, we would just link a Part directly to a Well, and say the Well has a certain volume.

What a Sample represents (abstracted) is the number of bottlenecking steps that a certain cell line has gone through, all of which represent potential for introducing mutations. Implementation wise, this is what "derived_from" is for - each bottlenecking step, we derive a new sample from our older sample. 

For example, we get a confirmed Sample from Twist (in both the form of raw DNA and in cells), we have a pretty good confidence that it is sequence correct. But lets say we passage it a couple of times in bacteria:

`Twist sample -> derived 1 -> derived 2 -> derived 3 -> derived 4 -> derived 5 -> derived 6 -> derived 7 -> derived 8`

If we only know that `Twist sample` is sequence confirmed, then we can say with pretty decent confidence that `derived 1` will also be sequence confirmed, assuming we did everything with good sterile technique. However, we might not be very confident that `derived 8` is sequence confirmed, because there has been time for the bacteria to evolve to make that gene more efficient for growth, often times just by bricking the gene (making it completely unusable by introducing mutations)

Stuff from Twist are not a bottlenecking step away from each other (they split the culture into glycerol, and then purify DNA from other parts of the culture), so they are the same Sample.

[continuing]

**Comment by vsoch** [comment]
Ah thank you for the clarification - that makes much more sense!

**Comment by Koeng101** [comment]
> I think what I'm hearing is that a sample, which is associated with wells (a group of many) and a part, given that the same part is import in a new plate, and given that the sample already exists for the part, we can add the new well to its list of wells, and the part stays the same.

ONLY if they are associated by FactoryOrder. The only time that it matters if a Sample already exists is that if that Sample exists and is associated with the same FactoryOrder.

> > FactoryOrder -> Plate -> Wells -> Samples -> Part

> That's a bit of circular logic, because we're running the create function that generates the relationship between those things to begin with. We can't do that lookup if we haven't created it yet (but we can do the logic that I'm walking through).

> so you are saying that the Sample.vendor (which will be the FactoryOrder id) is what determines if a sample exists or not - but won't every FactoryOrder have a new id by default? Are you saying that the Sample.vendor can't be the unique id of the particular order, but perhaps the name? So for the above, point 8 would be:

I'll go through my thoughts of the logic:

1. we check for all existing parts that we have based on their name, the "Name" field in the csv which links up to a gene_id for a Part
2. If a part doesn't already exist - throw an error to the user.
3. If all parts exist, make a Plate object.
4. For each row, make a Well object that goes within the Plate object
5. For each row, check if there is a Sample which relates to the Part gene_id that is already within the database and linked to the FactoryOrder. This can be expressed better in the form of a SQL query: 
```
SELECT s.uuid as sample_uuid
FROM parts AS p
JOIN samples AS s ON s.part_uuid=p.uuid
JOIN samples_wells AS sw ON sw.samples_uuid=s.uuid
JOIN wells AS w ON w.uuid=sw.wells_uuid
JOIN plates AS pl ON pl.uuid=w.plate_uuid
JOIN factoryorders AS fo ON fo.uuid=pl.order_uuid
WHERE p.gene_id = '{}'
AND fo.name = '{}'
```
That SQL query will then either give you zero rows or one row. If it is one row, place that sample_uuid into the Well object created above. If zero rows, produce a new Sample object, and put it into the well.

**Comment by vsoch** [comment]
Okay we just hit another issue with creating a well - an organism is required:

```
IntegrityError: null value in column "organism_id" violates not-null constraint
DETAIL:  Failing row contains (d4b3e526-d279-4568-a5ed-51e2aa48c755, H05, 0, 2000, , 2019-10-08 16:55:52.181735+00, 2019-10-08 16:55:52.181775+00, null).
```
Is this something that shouldn't be required?

**Comment by Koeng101** [comment]
> Is this something that shouldn't be required?

That should definitely note be required. Though, if there is a glycerol stock, that organism_id should default to Organism whose UUID == '0f8dc161-290c-4bcc-9892-d6637c8dfa26'. (Top10 is what they ship in)

**Comment by vsoch** [comment]
Your logic is clear except for this point:

> For each row, check if there is a Sample which relates to the Part gene_id that is already within the database and linked to the FactoryOrder. This can be expressed better in the form of a SQL query:

The function that we are running is to import the FactoryOrder, period. if you said "linked to the vendor for any FactoryOrder" that would be something that might exist, but linked to "the factory order that we are importing" is a case that will never be True.

**Comment by vsoch** [comment]
For now I'll make it not required.

**Comment by Koeng101** [comment]
> The function that we are running is to import the FactoryOrder, period. if you said "linked to the vendor for any FactoryOrder" that would be something that might exist, but linked to "the factory order that we are importing" is a case that will never be True.

Hmmmm. I thought we were talking about importing Plate Maps. FactoryOrders =/= Plates, since one FactoryOrder can contain many plates, but a plate may only be a part of one Order.

For importing FactoryOrders, we can just have humans input them, and then have an auto import script for Plates

**Comment by vsoch** [comment]
I think what you might mean to say:

> For each row, check if there is a Sample which relates to the Part gene_id that is already within the database AND the vendor name that is associated with the FactoryOrder.

**Comment by Koeng101** [comment]
> For each row, check if there is a Sample which relates to the Part gene_id that is already within the database AND the vendor name that is associated with the FactoryOrder.

We can get the same part from the same Vendor more than once, so we have to associate it with a FactoryOrder instead of a vendor (this changes once CompositeParts are completely implemented, but they aren't right now)

**Comment by Koeng101** [comment]
For each row, check if there is a Sample which relates to the Part gene_id that is already within the database AND the name of the FactoryOrder.

This makes sense to me^

**Comment by Koeng101** [comment]
>  "the factory order that we are importing" is a case that will never be True.

We can get FactoryOrders from Twist's API, but I don't think there is really a way we can easily import them, like we can Plate Maps. That's why whenever you are importing a Plate Map through the factory, the reverse will always be true: There will never be a time when you import a Plate Map without a FactoryOrder.

**Comment by vsoch** [comment]
When the user imports a plate map, they select a Vendor. This was requested in this issue:

 > When importing a plate, there should be the option to import it as associated with a DNA Order. Later, we can track which plates came from which particular orders.

The FactoryOrder is what I showed above - nothing more than a set of dates, linked to a vendor, with a list of plates. 

![image](https://user-images.githubusercontent.com/814322/66416690-62b2dc80-e9cc-11e9-8ec3-549ae7d295c4.png)

When the user is importing a plate map, they are likely going to create a new FactoryOrder. In this case, there are no linked plates. And if they click the checkbox to generate_samples, per your logic above, there will be no associated plates linked to the order in question, and thus nothing done further.

This is why (what I think) you mean to say is not to check for samples for the part associated with the particular order, but with _any_ FactoryOrder that has the vendor in question. "E.g., we already have a sample for this part from Twist, we don't need to generate it again."

**Comment by Koeng101** [comment]
> per your logic above, there will be no associated plates linked to the order in question, and thus nothing done further

I see where we're differing, will write out it out

**Comment by vsoch** [comment]
This is what makes sense to me.

> For each row, check if there is a Sample which relates to the Part gene_id that is already within the database AND the name of the _vendor associated with_ the FactoryOrder. 

The FactoryOrder, given that the plates and samples are generated based on importing the plate map, will by default not have plates linked to it, to start.

**Comment by Koeng101** [comment]
> The FactoryOrder is what I showed above - nothing more than a set of dates, linked to a vendor, with a list of plates.

If the people in operations are effective, there will never be a FactoryOrder that has a list of plates right from the get-go. They will be added sequentially as they come in.

> > Later, we can track which plates came from which particular orders.

Keyword is "later"

> And if they click the checkbox to generate_samples, per your logic above, there will be no associated plates linked to the order in question, and thus nothing done further.

The checkbox should be associated with the Plate Map import system, not the FactoryOrder. If the SQL query returns no rows, there aren't any Samples that exist, so generate new ones. After that initial generation, there WILL be associated Plates linked to the FactoryOrder, so the SQL query will return 1 row, which you'll use as the Sample object.

> The FactoryOrder, given that the plates and samples are generated based on importing the plate map, will by default not have plates linked to it, to start.

Yes!

>> vendor associated with the FactoryOrder

No - vendor doesn't matter in this circumstance. Vendor being associated with Samples and FactoryOrders are simply for data generation later (how many FactoryOrders did we get in from Twist? What is Twist's Sample sequencing like?) but has no relation to the current problem of Plate Map imports. As said above, we can order the exact same Part from the same Vendor twice, and it would generate two different samples (different bottlenecking steps if we ordered it Twice). The only time a new sample isn't generated is if there is already a Sample for a Part WITHIN a FactoryOrder.

**Comment by vsoch** [comment]
> The checkbox should be associated with the Plate Map import system, not the FactoryOrder.

You requested that a Plate Map import can be associated with an Order. This is a factory order.

> Link Plates to Orders: When importing a plate, there should be the option to import it as associated with a DNA Order. Later, we can track which plates came from which particular orders.

**Comment by vsoch** [comment]
> The only time a new sample isn't generated is if there is already a Sample for a Part WITHIN a FactoryOrder.

Factory Orders have plates, plates have wells, and wells can be linked to samples. So - I can definitely do this check, but in most cases it's not going to find anything and will generate a sample.

I'll just finish coding this up and submit for your review - if you see issue with the logic you can make suggestions directly to the code.

**Comment by vsoch** [comment]
oh, when you say within, do you mean already generated for the same plate map?

**Comment by Koeng101** [comment]
> You requested that a Plate Map import can be associated with an Order. This is a factory order.

I'm sorry, I was unclear on the terminology - I had put `Order` under the umbrella of `Factory`, so I thought that had made it clear or clearish - my bad.

> Factory Orders have plates, plates have wells, and wells can be linked to samples. So - I can definitely do this check, but in most cases it's not going to find anything and will generate a sample.

Actually, it'll precisely find a sample half of the time. For everything that is ordered, we get DNA of the part and cell lines with the part (both one sample). Otherwise, Twist doesn't ship it to us.

> I'll just finish coding this up and submit for your review - if you see issue with the logic you can make suggestions directly to the code.

That makes sense to me.

> oh, when you say within, do you mean already generated for the same plate map?

No, Twist will send us two different plates, one with DNA, and one with cells, both from the same order, and both containing the same samples in different forms.

**Comment by vsoch** [comment]
> I'm sorry, I was unclear on the terminology - I had put Order under the umbrella of Factory, so I thought that had made it clear or clearish - my bad.

Yes, so your referral to Order was referring to FactoryOrder - what exactly wasn't clear?

**Comment by Koeng101** [comment]
> You requested that a Plate Map import can be associated with an Order. This is a factory order.

> Yes, so your referral to Order was referring to FactoryOrder - what exactly wasn't clear?

Oh I thought the unclear part was that I didn't specify Order vs Factory order (ie, making difference between "Order" and "factory order")

**Comment by vsoch** [comment]
Okay I'll better explain, you said:

> The checkbox should be associated with the Plate Map import system, not the FactoryOrder.

And that isn't logical, because the checkbox is associated with the Plate Map import, which also requires the user to select an associated FactoryOrder.

**Comment by Koeng101** [comment]
> And that isn't logical, because the checkbox is associated with the Plate Map import, which also requires the user to select an associated FactoryOrder.

Is it not logical because of the associative links? I guess I could have been clearer and said the checkbox is directly associated with the Plate Map import system, and only indirectly associated with the FactoryOrder

**Comment by Koeng101** [comment]
> If all parts exist, make a Plate object.

It would appear that plate objects aren't created in https://github.com/vsoch/freegenes/pull/76/commits/fc66312281ded1fc8b8dc5149d1fdb361be2e88b #76 . Will actually open a different issue for this... Would like to be able to create new plate during input time, but for now will focus on uploading data.

**Comment by Koeng101** [comment]
https://github.com/vsoch/freegenes/issues/58#issuecomment-535128579

Plates should be imported like how I referenced in the issue comment if they don't already exist in our system.

**Comment by vsoch** [comment]
@Koeng101 plates are created - the only reason they wouldn't be is because all parts aren't found, per your specification above:

> I'm of the preference that we do not allow any importation of any plate map that doesn't have all parts within it represented in our database.

If all parts are defined, then the script proceeds to create plates, and by the logic that you outlined. 
 Could you please reference specific lines in the code and show me what is the current issue?

**Comment by vsoch** [comment]
This is where they are created - it's best to look at the full script since the referenced commit only shows sections relevant for the PR.

https://github.com/vsoch/freegenes/blob/master/fg/apps/factory/views/twist.py#L286toL321

**Comment by Koeng101** [comment]
Hmmm, I had uploaded all our previous Twist plates, and none of them went through.

For example, when I visit https://freegenes.dev/api/plates/?limit=1000 None of the plates I imported showed up, but there was no error message triggered by the system (they successfully imported the plates)

For example, I am pretty sure I added this plate, but it doesn't show up anywhere in the system. 

I think this might have something to do with the `if not container_id:`, since there isn't anywhere on the form to input a container https://freegenes.dev/f/twist/plates/import

**Comment by vsoch** [comment]
The import process has two steps - you first provide the sheet to get the plate ids lookup, and on success after the first submit an entire new form is presented where you must select not just container ids but also length height and name for each. It sounds like you didn’t get there - the error message should be printed to the top of he screen but if not take a look at the console for a message back from the server. Hopefully this isn’t a browser cookie thing.

**Comment by vsoch** [comment]
If the plate is is already found that’s another case that you wouldn’t see the second form - but again there should be a message. You aren’t allowed to import the same plate twice.

**Comment by Koeng101** [comment]
Yea I only imported new plates, manually checked to make sure I wasn't duplicating any plates or anything.

I never saw that form, would be great to see what the logs say. I did all the imports last night

**Comment by vsoch** [comment]
Can you give me one of the csv to test? I can add a save of the rows to pickle on the server, and then manually walk through it.

**Comment by Koeng101** [comment]
[plate map pSHPs0414B582235TN.csv.txt](https://github.com/vsoch/freegenes/files/3729942/plate.map.pSHPs0414B582235TN.csv.txt)

**Comment by vsoch** [comment]
okay - are you good with merging #92 and then I'll deploy and test this out?

**Comment by vsoch** [comment]
No wait you're totally right! It's returning the wrong template! Oy vey.

**Comment by vsoch** [comment]
See https://github.com/vsoch/freegenes/pull/92/commits/fcd3b7bab338749d3e68d4853b3d0d6db14f5ffa I think this should fix it.

**Comment by vsoch** [comment]
Locally now

![image](https://user-images.githubusercontent.com/814322/66843535-ea539a80-ef3a-11e9-9cba-7c4a5a997f95.png)

Let me know when the PR is good, I'll merge and update the view.

**Comment by Koeng101** [comment]
Approved PR.
