### ISSUE TITLE
Accidentally clicking on 'root' in the Lab Map brings you a 404

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#78]
**Describe the bug**
As described in title

**To Reproduce**
Go to https://freegenes.dev/f/map and double click root or visit https://freegenes.dev/f/undefined

**Expected behavior**
I would expect no redirects from opening or closing the root.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
Ah good catch! I made that node up :) I'll get in a fix asap (after cocoa!)

**Comment by vsoch** [comment]
Fixed with https://github.com/vsoch/freegenes/commit/489f22bee2794c2266c970445214da94dace66e4
