### ISSUE TITLE
Should plate deletion also delete wells?

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#79]
@Koeng101 right now when we delete a plate, we don't delete wells, and this is because it's a many to many relationship (and it's okay to not have any defined). However, logically I think we'd want to delete wells when we delete a plate. I would want/need to write a custom delete function to handle this. 

Also, when a well is deleted, should anything else be deleted (I would assume not, since a Part / Sample can have more than one well).

Thoughts?

**Comment by Koeng101** [comment]
> logically I think we'd want to delete wells when we delete a plate

I agree! There is nothing else I think we'd want to delete.

**Comment by vsoch** [comment]
Ok I’ll work on the delete function now.

**Comment by vsoch** [comment]
Pre-delete added! Apologies I meant to do it yesterday and then got hugely distracted with other things! But I wound up testing the other signals so it was good to take on today (needed more time than I anticipated).
