### ISSUE TITLE
Shipment Field Changes & Cosmetic Changes

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#83]
All the descriptions around the website get cut off if they're too long. We'd like there to be a way to either expand the description so that the full text could be seen, or make the box resize so that the whole text is visible by default.

Also, we'd like to change the fields attached to the Shipments. We'd like to keep the "Name" and "Status" fields the same, change the name of "Date Created" to "Date Ordered", remove the "Date Updated" field, add in a "Date Shipped" field (that would be blank until a shipment was created), and keep the "Signed MTA", "Notes", and "Distributions" fields the same.

Restated more simply, we'd like the fields "Name", "Status", "Date Ordered", "Date Shipped",  "Signed MTA", "Notes", and "Distributions".

Overall, this is fairly low priority stuff. If it's not quick and easy to implement, it can wait a bit.

**Comment by vsoch** [comment]
Could you please link the pages that you want the descriptions expanded on?

**Comment by vsoch** [comment]
hey @hverdonk there isn't a Date Created field, but there is time_created. There isn't a Date Updated field,  - but there is time_updated. Is this what you are referring to?

**Comment by vsoch** [comment]
Also - both of those date fields are auto generated. So I can't just change their names, but I can give you new fields to the model, so there will be time_created, time_updated, date_ordered, and date_shipped.

**Comment by vsoch** [comment]
Could you also please verify you are referring to an Order (fg.apps.orders.models.Order) and not a FactoryOrder (fg.apps.factory.models.FactoryOrder). Thanks!

-

**Comment by vsoch** [comment]
So - that's not a bug, there are no orders in the database:

```
from fg.apps.orders.models import *                                                                                      

Order.objects.count()                                                                                                    
0
```
I haven't been logged in or changed anything - @Koeng101 have you been interacting with the API? Or can anyone explain this?

**Comment by hverdonk** [comment]
I am referring to an order (and not a factory order). The dashboard fields normally refer to time_created (which includes a date) as "Date Created" - I'd like to change that name to "Date Ordered" without altering time_created.

I'd like the descriptions expanded on these pages:
https://freegenes.dev/dashboard
https://freegenes.dev/c/catalog/collections
https://freegenes.dev/c/catalog/distributions
https://freegenes.dev/c/catalog/parts

**Comment by Koeng101** [comment]
I haven't been interacting with the any deletes in the API...There should have been in previous updates. I wonder what is going on here.

**Comment by hverdonk** [comment]
Nope. But last time I was adding things to Orders, it was part of Main

**Comment by vsoch** [comment]
When was the last time you saw the orders? The only delete records I have in the logs are the following (you can check against your ip addresses)

```
uwsgi_1      | [pid: 23|app: 0|req: 2/14] 171.66.12.64 () {46 vars in 975 bytes} [Mon Oct  7 13:55:43 2019] GET /admin/main/order/9866da10-ed59-4921-955e-61fdf5014a82/delete/ => generated 3256 bytes in 525 msecs (HTTP/1.1 200) 7 headers in 395 bytes (1 switches on core 2)
uwsgi_1      | [pid: 31|app: 0|req: 8/16] 171.66.12.64 () {46 vars in 975 bytes} [Mon Oct  7 13:55:52 2019] GET /admin/main/order/9866da10-ed59-4921-955e-61fdf5014a82/delete/ => generated 3256 bytes in 35 msecs (HTTP/1.1 200) 7 headers in 395 bytes (1 switches on core 0)
uwsgi_1      | [pid: 28|app: 0|req: 1/17] 171.66.12.64 () {50 vars in 1090 bytes} [Mon Oct  7 13:55:54 2019] POST /admin/main/order/9866da10-ed59-4921-955e-61fdf5014a82/delete/ => generated 0 bytes in 466 msecs (HTTP/1.1 302) 8 headers in 468 bytes (1 switches on core 0)
uwsgi_1      | [pid: 27|app: 0|req: 270/694] 171.66.12.60 () {46 vars in 993 bytes} [Tue Oct  8 12:40:43 2019] GET /admin/main/institution/445ab52e-78ec-4c98-a5c9-263b256eed5a/delete/ => generated 3292 bytes in 42 msecs (HTTP/1.1 200) 7 headers in 395 bytes (1 switches on core 1)
uwsgi_1      | [pid: 31|app: 0|req: 325/695] 171.66.12.60 () {50 vars in 1108 bytes} [Tue Oct  8 12:40:51 2019] POST /admin/main/institution/445ab52e-78ec-4c98-a5c9-263b256eed5a/delete/ => generated 0 bytes in 32 msecs (HTTP/1.1 302) 8 headers in 476 bytes (1 switches on core 3)
```

**Comment by vsoch** [comment]
wait you might be on to something - the app_label for Order was incorrect labeled as main. I "fixed" it but I'll try changing it back just in case.

**Comment by Koeng101** [comment]
No, we can't, but there was definitely a time that Shipments/Orders came up in the Dashboard, and Monday + Tuesday of this week Hannah was adding in new Shipments/Orders.

**Comment by hverdonk** [comment]
That would make sense - when I said "Orders was part of Main", my frame of reference was the Django admin site. Up until yesterday, "Orders" was under the "Main" heading

**Comment by vsoch** [comment]
Yes, and I can confirm that's exactly what happens - when you change that little piddley string it totally deletes the model and recreates it in another app, regardless of the location.

```
root@5030de6c0281:/code# python manage.py makemigrations
Migrations for 'main':
  fg/apps/main/migrations/0008_order.py
    - Create model Order
Migrations for 'orders':
  fg/apps/orders/migrations/0002_delete_order.py
    - Delete model Order
```
This is totally my fault, I didn't even know it worked liked that, and I can't fix it. I'm really sorry guys :(

**Comment by Koeng101** [comment]
Woops!

**Comment by Koeng101** [comment]
The data is completely recoverable from our other APIs, but like we should create contingency cases so this doesn't happen again.

**Comment by vsoch** [comment]
Yes we definitely should - and this is the weirdest case of deletion, I didn't even know something like that could happen.

**Comment by hverdonk** [comment]
At least this only happened with ~15 orders - I'd rather this mistake happen early than later

**Comment by Koeng101** [comment]
It'll take us a bit of time to put the data back in, but at least we can be more sure of data quality as it goes back in. Just like, let's make sure this doesn't happen at a time where we get real screwed

**Comment by vsoch** [comment]
I have backup scripts that are meant to run nightly, but for some reason the cron job produced empty files (and running it interactively now I get data, ug). It must be something about pipes, I'll look into it.

**Comment by Koeng101** [comment]
Good thing we caught it!

**Comment by vsoch** [comment]
I think the difference comes down to this:

```bash
python /code/manage.py dumpdata $db > /code/backup/$db.json
```
Needing to be

```bash
python /code/manage.py dumpdata $db --output /code/backup/$db.json
```
I'll make the change and check the run for tomorrow!

**Comment by vsoch** [comment]
@hverdonk can you add at least one order sometime today, so when I check tomorrow I can verify if it is backing up properly?

**Comment by hverdonk** [comment]
Sure! I'll add back one of the FedEx ones and email you the JSON with the right label links again.

**Comment by vsoch** [comment]
Shipment fields are added:

![image](https://user-images.githubusercontent.com/814322/66516579-53588f80-eaaf-11e9-80b4-c5af40e169d0.png)

And all catalog (detail tables) have expanded descriptions.
