### ISSUE TITLE
Parts linked to Orders

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#85]
In order to tell what we have ordered in an FactoryOrder, I would like for there to be a way to link parts directly to FactoryOrders, basically to say "we expect for these parts to arrive in this FactoryOrder". This way, we can take the difference between what arrived and what we expect, to find how many genes failed the synthesis process.

From Twist, each order gets a CSV file with all parts in it. This CSV has several headers, but the one we care about is "Name", under which each part gene_id is listed.

If we could somehow connect these two tables, we can get much better querying later for parts that failed synthesis or cloning.

**Comment by vsoch** [comment]
So just to verify - right now we already have plates linked to FactoryOrders

```
    # One or more plates can be added to an order
    plates = models.ManyToManyField('main.Plate', blank=True, default=None,
                                    related_name="factoryorder_plates",
                                    related_query_name="factoryorder_plates")
```
and Parts -> Wells -> Sample and Part

but you'd like to also add a link to Parts? Is the idea that you would know in advance Parts that are expected (how?) and then manually select them when you create a FactoryOrder?

**Comment by Koeng101** [comment]
> Is the idea that you would know in advance Parts that are expected (how?) and then manually select them when you create a FactoryOrder?

You would know the Parts that are expected because they are linked to the FactoryOrder.

The idea is to not manually select them, but to give the FactoryOrder the CSV file that we ordered with.

**Comment by vsoch** [comment]
We're getting circular again - if this is reliant on the Plate Map import, and it's importing to a newly created FactoryOrder, you are asking to check for a set of Parts at the same time you are adding them to the FactoryOrder. Is there some other import that is done to associate parts with a FactoryOrder that would happen before importing the PlateMap? This import plate map function is hugely overloaded at this point.

**Comment by Koeng101** [comment]
> if this is reliant on the Plate Map import

This is completely separate from Plate Map, and as fair as the plate map function is concerned, absolutely unrelated.

> Is there some other import that is done to associate parts with a FactoryOrder that would happen before importing the PlateMap? 

We give the FactoryOrder the CSV file of genes that we ordered, which is different from the Plate Map imports.

**Comment by vsoch** [comment]
Oh that makes me so happy, I was so worried, haha.

Could you please send me an example csv file of genes ordered? And where would you like a button to do this import, from the main Factory page under Twist, something like "Import Order Genes" and then the user would select a factory order and do the import?

**Comment by Koeng101** [comment]
> And where would you like a button to do this import, from the main Factory page under Twist, something like "Import Order Genes" and then the user would select a factory order and do the import?

Perfect!

**Comment by vsoch** [comment]
@Koeng101 in the case that the part doesn't exist (likely) do we:

 - exit and tell the user no go.
 - add parts that don't exist to the database

In the case of the latter, I need to know the complete mapping between the header fields and the part object. Here are the relevant headers:

```
		['Name',
		 'Insertion site name',
		 'Vector name',
		 'Insert length',
		 'Construct length',
		 'Insert sequence',
		 'Construct sequence',
		 'Step',
		 'Shipping est']
```

**Comment by Koeng101** [comment]
> exit and tell the user no go

This one

> In the case of the latter, I need to know the complete mapping between the header fields and the part object. Here are the relevant headers:

The only necessary part should be the 'Name' column, which maps to the part gene_id

**Comment by vsoch** [comment]
okay, so just to confirm, the example csv you game me (since we don't have the Parts in the current database) would not be imported.

**Comment by vsoch** [comment]
Also, in the case that we do have all the parts, you are saying we only need to define the gene_id. Since there are other fields required, you are saying that you want to change the model so that the only required field for a Part is a gene_id.

**Comment by vsoch** [comment]
Actually sorry just contradicted myself! If we don't allow import unless all parts are there, then there is no import, and we don't need to know about those fields. We exit and no go.

**Comment by Koeng101** [comment]
> okay, so just to confirm, the example csv you game me (since we don't have the Parts in the current database) would not be imported.

Correct, I still need to import these parts into the current database. Sorry about giving you a csv file that I haven't imported parts into the database yet of! Here is a good csv file

> Actually sorry just contradicted myself!

All good, just for a note with the factory - we'll never be importing new Parts from physical synthesis providers. That might clarify things!

[OpenEnzyme.csv.txt](https://github.com/vsoch/freegenes/files/3725979/OpenEnzyme.csv.txt)

**Comment by vsoch** [comment]
Nice job on the +.txt trick! :)

**Comment by vsoch** [comment]
Twist Parts Import added -> https://vsoch.github.io/freegenes/docs/usage/interface#import-twist-parts
