### ISSUE TITLE
Edit Shipments

### ISSUE THREAD

**Issue by hverdonk** [vsoch/freegenes#86]
**Describe the bug**
I created a shipment in the admin panel. I then went back to freegenes.dev to add the Implementing Letter, but when I clicked on the order to view its associated information, I triggered a crash.

**To Reproduce**
Go to the [dashboard](https://freegenes.dev/dashboard) and select the order "OpenEnzyme - Scintia"

**Expected behavior**
The page should display the dictionary of information associated with the order.

If applicable, add versions and screenshots to help explain your problem.
<img width="1190" alt="Screen Shot 2019-10-09 at 12 56 03 PM" src="https://user-images.githubusercontent.com/31907124/66515566-31054880-ea94-11e9-8da1-c14c86b65c40.png">
This thing.

**Comment by vsoch** [comment]
That was more of the previous - the main -> order change also changed the URL. It's working now!
