### ISSUE TITLE
plate_vendor_id is not returned by API

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#88]
**Describe the bug**
The plate_vendor_id field in the Plates class is not returned through the API.

**To Reproduce**
`requests.get('https://freegenes.dev/api/plates/{}'.format('fd95f3e2-354b-412a-82f6-dca8cb9e6db1')).json()`

**Expected behavior**
The plate_vendor_id be returned as an key:value within the request response.

If applicable, add versions and screenshots to help explain your problem.

**Comment by vsoch** [comment]
Now it is :)
