### ISSUE TITLE
Get feedback about strategies for storing sequence data in postgres

### ISSUE THREAD

**Issue by vsoch** [vsoch/freegenes#9]
The absolute minimum is 10K, more reasonable is 100K, and (ideally) we'd want ~4 million but [this is not practical](https://dba.stackexchange.com/questions/189876/size-limit-of-character-varying-postgresql). I'll post various feedback that I get here. In the meantime, the sequences are set to 100K, because it's within the limit. We can adjust if we find a better strategy.

 - I would use a TEXT type,  or move to a JSON data store which Postgres has now,    but yeah I never did anything that large, (Campus Champions slack)

.... more coming when I hear back.

**Comment by vsoch** [comment]
From Singularity slack:

> You can happily stuff very large things into fields. Most sensible DB’s store them in the main table as pointers to off-page data, so they are happy storing that.
> Used to be very common (before S3 and cloudy object stores) to stuff images, and other large blobs in DBs without much issue
> In postgres it uses something called TOAST to store large stuff - you can read about that here: https://www.postgresql.org/docs/10/storage-toast.html
> What you don’t want to do is attempt to index or query over very large fields - but storing them isn’t too much of an issue (edited)
> Also note that generally, RDBMS is better than NoSQL databases for this. e.g. Mongo has a maximum document size of 16MB. Postgres has a maximum row size of 1.6TB, and field size of 1GB.
> I’ve done this type of thing in a pipeline that used a MySQL backend, and stored protein sequence data, and encoded mass spectra. Grew to >2TB of data in the DB without issue.
> @v - see e.g. https://proteomics.swmed.edu/confetti/

This seems like strong advice - it looks like we'd want to use [TextField](https://docs.djangoproject.com/en/2.2/ref/models/fields/#textfield) instead of CharField, and Django should handle it automatically (with LZ compression). TextField also doesn't require a max length.

**Comment by vsoch** [comment]
Another idea (that was my first instinct) that we should consider - just storing as a file in object storage. If query is inefficient anyway, storing as a file might be reasonable to not rely on the database. We would want to discuss how the data is interacted with (for example, downloads with egress can add up over time, although these files don't seem big enough for that to be the case).

**Comment by vsoch** [comment]
> It’s  faster to pull pages out of the database then go and look up the file, open it, read it in…. or (worse) retrieve it from an object store.
> Also, as mentioned above, the support for doing this came before S3 etc was widespread

I think my instinct is to use files, unless there is a huge rationale for not. @Koeng101 I'm going to create an issue where we can put single questions that are for discussion with the rest of the team, this will be one of them.

**Comment by Koeng101** [comment]
One thing to note about
