### ISSUE TITLE
"Production Board" for the Factory

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#91]
We would like a production board for the orders currently in the database:

Basically, this will display a few pieces of information in a basic table.

`Order name, number of parts(total), status, estimated price`

And if `status` == `'Completed'`, we have a few more columns

` number of parts(completed), number of parts(failed), How long the order took (time end - time start), real price`.

For each category with `parts`, there should be a clickable link to a view those parts.

**Comment by vsoch** [comment]
Also just a heads up, we are going to essentially be duplicating this admin table that already exists: 
![image](https://user-images.githubusercontent.com/814322/66836142-cf7b2900-ef2e-11e9-9026-76ae735f6e84.png)

**Comment by vsoch** [comment]
This is what you want to do?

**Comment by vsoch** [comment]
For the parts - given the example we are working with (the last import for the FactoryOrder you provided me) none of the parts actually have a status, so I am not sure how to render the number of failed, completed, etc.

**Comment by vsoch** [comment]
Parts also don't have a "Completed" status:

```
[('null', None),
 ('optimized', 'optimized'),
 ('fixed', 'fixed'),
 ('sites_applied', 'sites_applied'),
 ('syn_checked', 'syn_checked'),
 ('syn_checked_failed', 'syn_checked_failed')]
```

**Comment by Koeng101** [comment]
> Also just a heads up, we are going to essentially be duplicating this admin table that already exists:

Yes! With the exception, that down the line, we want for all that information to be publicly available (other than price) eventually

> Parts also don't have a "Completed" status:

I think we should probably remove `Part.status`, since that's all legacy information we don't really need anymore.

Basically, you can know if a `Part` failed in a `FactoryOrder` whose status is set to `Complete`, because although it is linked with the many-to-many table to the `FactoryOrder`, there is no `Sample` for that `Part` linked to the `FactoryOrder`. Similarly, we know if a `Part` is complete in a `FactoryOrder` because there IS a `Sample` that exists that is associated with that specific `Part`.

Unfortunately, this doesn't really work until we have all the plates in the system, which there is something funky going on in other issue that needs to be worked out first.

**Comment by vsoch** [comment]
I'd suggest that (for now) we leave the Part.status field, and leave the custom parsing for completed/ failed out until the other issue is resolved. The reason is because deriving the status sounds like it's going to be dependent on querying other objects, and we'd want to cache that by storing it in that field.

**Comment by Koeng101** [comment]
Part.status does denormalize the database though, since parts can be ordered more than once. The status can really only be derived by looking for samples - which isn't that hard of a query on the database.

Could we get `Completed Parts,Failed Parts` on the Production Board? This could be adding values to "Number of Parts" or by adding new columns.

We'd also like for those links to be clickable, rather than having another "Parts" column.

**Comment by vsoch** [comment]
Could you please provide the query to derive completed and failed?

**Comment by vsoch** [comment]
Just having a sample (or > 0 samples) associated == success?

**Comment by Koeng101** [comment]
Yep! If a sample for a part exists within a plate associated with that factory order, that part is successful within that order
