### ISSUE TITLE
Sort Production Board by date

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#95]
**Is your feature request related to a problem? Please describe.**

I would like there to be a field added to the production board for the start date of a `FactoryOrder`, and for `FactoryOrder`s to be sorted by their start date (so that the oldest order is at the bottom)

**Describe the solution you'd like**
^
**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
If dataTables works, this should provide sortable columns. I'm not sure why it's not rendering (I'll look into it). With datatables, akin to the orders table, you'd be able to sort by whatever you please.
