### ISSUE TITLE
"Completed", "Failed", and "Total" link to a part list

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#96]
**Is your feature request related to a problem? Please describe.**
I would like to be able to click on the Factory Production Board's "Complete", "Failed", and "Total", and be brought to a `Part` list of the parts in that category for each given `FactoryOrder`

(More details here - https://github.com/vsoch/freegenes/issues/91#issuecomment-542292239 ) 

**Describe the solution you'd like**
As above^

**Describe alternatives you've considered**
I was thinking of making an API endpoint for this, which I could do and then we could reuse the function from there. Alternatively, this might be pretty easy to do, and so it would be worth to just implement

Anything else?

**Comment by vsoch** [comment]
so basically - the view parts view (table), but filtered to each set?

**Comment by Koeng101** [comment]
Yep!

**Comment by vsoch** [comment]
This is all set:

https://freegenes.dev/f/

I removed the "parts" column from the table, as the counts column now links to each of completed, failed, and total, respectively.
