### ISSUE TITLE
Make "generate sample" not optional

### ISSUE THREAD

**Issue by Koeng101** [vsoch/freegenes#98]
**Is your feature request related to a problem? Please describe.**
Through adding samples into our system from Twist, I've found the "generate sample" button on the Factory Plate Import page to be pretty annoying - there aren't any circumstances where we wouldn't want to generate samples, and I believe I forgot to press it at least once, which is causing some inconsistencies in the data (Figuring that out now)

**Describe the solution you'd like**
Removal of the option to generate sample (don't want anyone to accidentally click it), and make it generate samples by default

**Describe alternatives you've considered**

Anything else?

**Comment by vsoch** [comment]
okay, will remove this field.
